package com.siga.ws;
/**
 * NO MODIFICAR. Clase generada con GeneraConstantesXSD
 */

/**
 * @author angelcpe
 *
 */
public interface PCAJGConstantes {

     /***** CAMPOS DE LA VISTA V_PCAJG_EJG ****/

	public final String IDREMESA = "IDREMESA";
	public final String IDINSTITUCION = "IDINSTITUCION";
	public final String IDTIPOEJG = "IDTIPOEJG";
	public final String ANIO = "ANIO";
	public final String NUMERO = "NUMERO";
	public final String NUMEJG = "NUMEJG";
	public final String TIPOINTERCAMBIO = "TIPOINTERCAMBIO";
	public final String ORIGENINTERCAMBIO_CDA = "ORIGENINTERCAMBIO_CDA";
	public final String DESTINOINTERCAMBIO_CDA = "DESTINOINTERCAMBIO_CDA";
	public final String IDENTIFICADORINTERCAMBIO = "IDENTIFICADORINTERCAMBIO";
	public final String VERSION_PCAJG = "VERSION_PCAJG";
	public final String VERSION_XSD_GENERALITAT = "3.2";
	public final String DE_CE_COLEGIOEXPEDIENTE = "DE_CE_COLEGIOEXPEDIENTE";
	public final String DE_CE_NUMEXPEDIENTE = "DE_CE_NUMEXPEDIENTE";
	public final String DE_CE_ANYOEXPEDIENTE = "DE_CE_ANYOEXPEDIENTE";
	public final String DE_CES_ORIGENEXPEDIENTESERVICI = "DE_CES_ORIGENEXPEDIENTESERVICI";
	public final String DE_CES_NUMEXPEDIENTESERVICIO = "DE_CES_NUMEXPEDIENTESERVICIO";
	public final String DE_CES_ANYOEXPEDIENTESERVICIO = "DE_CES_ANYOEXPEDIENTESERVICIO";
	public final String DE_FECHASOLICITUD = "DE_FECHASOLICITUD";
	public final String DE_OBSERVACIONES2 = "DE_OBSERVACIONES2";
	public final String PD_PD_BAJAPROCURADORDESIGNADO = "PD_PD_BAJAPROCURADORDESIGNADO";
	public final String PD_PD_DP_COLEGIOPROCURADOR = "PD_PD_DP_COLEGIOPROCURADOR";
	public final String PD_PD_DP_NUMCOLEGIADOPROCURADO = "PD_PD_DP_NUMCOLEGIADOPROCURADO";
	public final String PD_PD_DP_NOMBRECOMPLETOPROCURA = "PD_PD_DP_NOMBRECOMPLETOPROCURA";
	public final String PD_PD_FECHADESIGNACIONPROCURAD = "PD_PD_FECHADESIGNACIONPROCURAD";
	public final String PD_PD_NUMDESIGNACIONPROCURADOR = "PD_PD_NUMDESIGNACIONPROCURADOR";
	public final String IDPERSONA = "IDPERSONA";
	public final String DS_DP_TIPOPERSONA_CDA = "DS_DP_TIPOPERSONA_CDA";
	public final String DS_DP_TIPOIDENTIFICACION_CDA = "DS_DP_TIPOIDENTIFICACION_CDA";
	public final String DS_DP_IDENTIFICACION = "DS_DP_IDENTIFICACION";
	public final String DS_DP_NOMBRE = "DS_DP_NOMBRE";
	public final String DS_DP_PRIMERAPELLIDO = "DS_DP_PRIMERAPELLIDO";
	public final String DS_DP_SEGUNDOAPELLIDO = "DS_DP_SEGUNDOAPELLIDO";
	public final String DS_DP_RAZONSOCIAL = "DS_DP_RAZONSOCIAL";
	public final String DS_DP_FECHANACIMIENTO = "DS_DP_FECHANACIMIENTO";
	public final String DS_DP_NACIONALIDAD_CDA = "DS_DP_NACIONALIDAD_CDA";
	public final String DS_DP_SITUACIONLABORAL_CDA = "DS_DP_SITUACIONLABORAL_CDA";
	public final String DS_DP_PROFESION_CDA = "DS_DP_PROFESION_CDA";
	public final String DS_DP_SEXO = "DS_DP_SEXO";
	public final String DS_DP_IDIOMACOMUNICACION = "DS_DP_IDIOMACOMUNICACION";
	public final String DS_DP_ESTADOCIVIL_CDA = "DS_DP_ESTADOCIVIL_CDA";
	public final String DS_DP_REGIMENECONOMICO_CDA = "DS_DP_REGIMENECONOMICO_CDA";
	public final String DS_DP_NUMHIJOS = "DS_DP_NUMHIJOS";
	public final String DS_DP_FECHAFORMALIZACION = "DS_DP_FECHAFORMALIZACION";
	public final String DS_DP_TIPOPERSONAJURIDICA_CDA = "DS_DP_TIPOPERSONAJURIDICA_CDA";
	public final String DS_DP_TIPODOMICILIO_CDA = "DS_DP_TIPODOMICILIO_CDA";
	public final String DS_DP_DD_TIPOVIA_CDA = "DS_DP_DD_TIPOVIA_CDA";
	public final String DS_DP_DD_NOMBREVIA = "DS_DP_DD_NOMBREVIA";
	public final String DS_DP_DD_NUMERODIRECCION = "DS_DP_DD_NUMERODIRECCION";
	public final String DS_DP_DD_ESCALERADIRECCION = "DS_DP_DD_ESCALERADIRECCION";
	public final String DS_DP_DD_PISODIRECCION = "DS_DP_DD_PISODIRECCION";
	public final String DS_DP_DD_PUERTADIRECCION = "DS_DP_DD_PUERTADIRECCION";
	public final String DS_DP_DD_PAIS_CDA = "DS_DP_DD_PAIS_CDA";
	public final String DS_DP_DD_PROVINCIA_CDA = "DS_DP_DD_PROVINCIA_CDA";
	public final String DS_DP_DD_M_MUNICIPIO_CDA = "DS_DP_DD_M_MUNICIPIO_CDA";
	public final String DS_DP_DD_M_SUBCODIGOMUNICIPIO = "DS_DP_DD_M_SUBCODIGOMUNICIPIO";
	public final String DS_DP_DD_CODIGOPOSTAL = "DS_DP_DD_CODIGOPOSTAL";
	public final String DS_DC_NUMEROTELEFONO1 = "DS_DC_NUMEROTELEFONO1";
	public final String DS_DC_NUMEROTELEFONO2 = "DS_DC_NUMEROTELEFONO2";
	public final String DS_DC_EMAIL = "DS_DC_EMAIL";
	public final String DS_DEP_I_CONCEPTOINGRESOS_CDA = "DS_DEP_I_CONCEPTOINGRESOS_CDA";
	public final String DS_DEP_I_OBSERVACIONESINGRESOS = "DS_DEP_I_OBSERVACIONESINGRESOS";
	public final String DS_DEP_I_DESCRIPCIONINGRESOS = "DS_DEP_I_DESCRIPCIONINGRESOS";
	public final String DS_DEP_I_IMPORTEBRUTO = "DS_DEP_I_IMPORTEBRUTO";
	public final String DS_DEP_I_ACUMULABLE = "DS_DEP_I_ACUMULABLE";
	public final String DS_DEP_PBI_TIPOBIENINMUEBL_CDA = "DS_DEP_PBI_TIPOBIENINMUEBL_CDA";
	public final String DS_DEP_PBI_ORIGENVALORACIO_CDA = "DS_DEP_PBI_ORIGENVALORACIO_CDA";
	public final String DS_DEP_PBI_CARGAS = "DS_DEP_PBI_CARGAS";
	public final String DS_DEP_PBI_OBSERVACIONES = "DS_DEP_PBI_OBSERVACIONES";
	public final String DS_DEP_PBI_VALORACIONECONOMICA = "DS_DEP_PBI_VALORACIONECONOMICA";
	public final String DS_DEP_PBI_ACUMULABLE = "DS_DEP_PBI_ACUMULABLE";
	public final String DS_DEP_PBM_TIPOBIENMUEBLE_CDA = "DS_DEP_PBM_TIPOBIENMUEBLE_CDA";
	public final String DS_DEP_PBM_OBSERVACIONES = "DS_DEP_PBM_OBSERVACIONES";
	public final String DS_DEP_PBM_VALORACIONECONOMICA = "DS_DEP_PBM_VALORACIONECONOMICA";
	public final String DS_DEP_PBM_ACUMULABLE = "DS_DEP_PBM_ACUMULABLE";
	public final String DS_DEP_PBO_CARGAS = "DS_DEP_PBO_CARGAS";
	public final String DS_DEP_PBO_DESCRIPCIONBIEN = "DS_DEP_PBO_DESCRIPCIONBIEN";
	public final String DS_DEP_PBO_OBSERVACIONES = "DS_DEP_PBO_OBSERVACIONES";
	public final String DS_DEP_PBO_VALORACIONECONOMICA = "DS_DEP_PBO_VALORACIONECONOMICA";
	public final String DS_DEP_PBO_ACUMULABLE = "DS_DEP_PBO_ACUMULABLE";
	public final String DS_DEP_OTROSDATOSECONOMICOS = "DS_DEP_OTROSDATOSECONOMICOS";
	public final String DR_DP_TIPOPERSONA_CDA = "DR_DP_TIPOPERSONA_CDA";
	public final String DR_DP_TIPOIDENTIFICACION_CDA = "DR_DP_TIPOIDENTIFICACION_CDA";
	public final String DR_DP_IDENTIFICACION = "DR_DP_IDENTIFICACION";
	public final String DR_DP_NOMBRE = "DR_DP_NOMBRE";
	public final String DR_DP_PRIMERAPELLIDO = "DR_DP_PRIMERAPELLIDO";
	public final String DR_DP_SEGUNDOAPELLIDO = "DR_DP_SEGUNDOAPELLIDO";
	public final String DR_DP_RAZONSOCIAL = "DR_DP_RAZONSOCIAL";
	public final String DR_DP_FECHANACIMIENTO = "DR_DP_FECHANACIMIENTO";
	public final String DR_DP_NACIONALIDAD_CDA = "DR_DP_NACIONALIDAD_CDA";
	public final String DR_DP_SITUACIONLABORAL_CDA = "DR_DP_SITUACIONLABORAL_CDA";
	public final String DR_DP_PROFESION_CDA = "DR_DP_PROFESION_CDA";
	public final String DR_DP_SEXO = "DR_DP_SEXO";
	public final String DR_DP_IDIOMACOMUNICACION = "DR_DP_IDIOMACOMUNICACION";
	public final String DR_DP_ESTADOCIVIL_CDA = "DR_DP_ESTADOCIVIL_CDA";
	public final String DR_DP_REGIMENECONOMICO_CDA = "DR_DP_REGIMENECONOMICO_CDA";
	public final String DR_DP_NUMHIJOS = "DR_DP_NUMHIJOS";
	public final String DR_DP_FECHAFORMALIZACION = "DR_DP_FECHAFORMALIZACION";
	public final String DR_DP_TIPOPERSONAJURIDICA_CDA = "DR_DP_TIPOPERSONAJURIDICA_CDA";
	public final String DR_DP_TIPODOMICILIO_CDA = "DR_DP_TIPODOMICILIO_CDA";
	public final String DR_DP_DD_TIPOVIA_CDA = "DR_DP_DD_TIPOVIA_CDA";
	public final String DR_DP_DD_NOMBREVIA = "DR_DP_DD_NOMBREVIA";
	public final String DR_DP_DD_NUMERODIRECCION = "DR_DP_DD_NUMERODIRECCION";
	public final String DR_DP_DD_ESCALERADIRECCION = "DR_DP_DD_ESCALERADIRECCION";
	public final String DR_DP_DD_PISODIRECCION = "DR_DP_DD_PISODIRECCION";
	public final String DR_DP_DD_PUERTADIRECCION = "DR_DP_DD_PUERTADIRECCION";
	public final String DR_DP_DD_PAIS_CDA = "DR_DP_DD_PAIS_CDA";
	public final String DR_DP_DD_PROVINCIA_CDA = "DR_DP_DD_PROVINCIA_CDA";
	public final String DR_DP_DD_M_MUNICIPIO_CDA = "DR_DP_DD_M_MUNICIPIO_CDA";
	public final String DR_DP_DD_M_SUBCODIGOMUNICIPIO = "DR_DP_DD_M_SUBCODIGOMUNICIPIO";
	public final String DR_DP_DD_CODIGOPOSTAL = "DR_DP_DD_CODIGOPOSTAL";
	public final String DR_DC_NUMEROTELEFONO1 = "DR_DC_NUMEROTELEFONO1";
	public final String DR_DC_NUMEROTELEFONO2 = "DR_DC_NUMEROTELEFONO2";
	public final String DR_DC_EMAIL = "DR_DC_EMAIL";
	public final String DDJ_PARTIDOJUDICIAL_CDA = "DDJ_PARTIDOJUDICIAL_CDA";
	public final String DDJ_JURISDICCION_CDA = "DDJ_JURISDICCION_CDA";
	public final String DDJ_ORGANOJUDICIAL_CDA = "DDJ_ORGANOJUDICIAL_CDA";
	public final String DDJ_TIPOPROCEDIMIENTO_CDA = "DDJ_TIPOPROCEDIMIENTO_CDA";
	public final String DDJ_IDENTIFICADORPROCEDIMIENTO = "DDJ_IDENTIFICADORPROCEDIMIENTO";
	public final String DDJ_RESUMENPRETENSION = "DDJ_RESUMENPRETENSION";
	public final String DDJ_RENUNCIADESIGNACION = "DDJ_RENUNCIADESIGNACION";
	public final String DDJ_RENUNCIAHONORARIOS = "DDJ_RENUNCIAHONORARIOS";
	public final String DDJ_DEMANDADODEMANDANTE = "DDJ_DEMANDADODEMANDANTE";
	public final String DDJ_PRECEPTIVO_CDA = "DDJ_PRECEPTIVO_CDA";
	public final String DAD_NUMEROATESTADO = "DAD_NUMEROATESTADO";
	public final String DAD_FECHAASISTENCIAATESTADO = "DAD_FECHAASISTENCIAATESTADO";
	public final String DAD_CENTRODETENCION_CDA = "DAD_CENTRODETENCION_CDA";
	public final String DAD_NUMERODILIGENCIA = "DAD_NUMERODILIGENCIA";
	public final String DAD_FECHAASISTENCIADILIGENCIA = "DAD_FECHAASISTENCIADILIGENCIA";
	public final String DAD_ORGANOJUDICIAL_CDA = "DAD_ORGANOJUDICIAL_CDA";
	public final String DAD_AA_NUMCOLEGIADOABOGADO = "DAD_AA_NUMCOLEGIADOABOGADO";
	public final String DAD_ESATESTADO = "DAD_ESATESTADO";
	public final String DTE_TA_IT_ESTADOEXPEDIENTE_CDA = "DTE_TA_IT_ESTADOEXPEDIENTE_CDA";
	public final String DTE_TA_IT_FECHAESTADO = "DTE_TA_IT_FECHAESTADO";
	public final String DTE_TD_IT_ESTADOEXPEDIENTE_CDA = "DTE_TD_IT_ESTADOEXPEDIENTE_CDA";
	public final String DTE_TD_IT_FECHAESTADO = "DTE_TD_IT_FECHAESTADO";
	public final String DTE_TD_TIPODICTAMEN_CDA = "DTE_TD_TIPODICTAMEN_CDA";
	public final String DTE_TD_MOTIVODICTAMEN_CDA = "DTE_TD_MOTIVODICTAMEN_CDA";
	public final String DTE_TD_INTERVALOINGRESOSRECURS = "DTE_TD_INTERVALOINGRESOSRECURS";
	public final String DTE_TD_OBSERVACIONESDICTAMEN = "DTE_TD_OBSERVACIONESDICTAMEN";
	public final String DTE_TR_IT_ESTADOEXPEDIENTE_CDA = "DTE_TR_IT_ESTADOEXPEDIENTE_CDA";
	public final String DTE_TR_IT_FECHAESTADO = "DTE_TR_IT_FECHAESTADO";
	public final String DTE_TR_IDENTIFICADORRESOLUCION = "DTE_TR_IDENTIFICADORRESOLUCION";
	public final String DTE_TR_TIPORESOLUCION_CDA = "DTE_TR_TIPORESOLUCION_CDA";
	public final String DTE_TR_MOTIVORESOLUCION_CDA = "DTE_TR_MOTIVORESOLUCION_CDA";
	public final String DTE_TR_INTERVALOINGRESOSRECURS = "DTE_TR_INTERVALOINGRESOSRECURS";
	public final String DTE_TR_PR_TIPOPRESTACION_CDA = "DTE_TR_PR_TIPOPRESTACION_CDA";


     /***** CAMPOS DE LA VISTA V_PCAJG_ABOGADOSDESIGNADOS ****/

	public final String PD_AD_AD_BAJAABOGADODESIGNADO = "PD_AD_AD_BAJAABOGADODESIGNADO";
	public final String PD_AD_AD_NUMCOLEGIADOABOGADO = "PD_AD_AD_NUMCOLEGIADOABOGADO";
	public final String PD_AD_AD_FECHADESIGNACIONABOGA = "PD_AD_AD_FECHADESIGNACIONABOGA";
	public final String PD_AD_AD_NUMDESIGNACIONABOGADO = "PD_AD_AD_NUMDESIGNACIONABOGADO";
	public final String PD_AD_AD_NOMBRECOMPLETOABO = "PD_AD_AD_NOMBRECOMPLETOABO";
	public final String PD_AD_AD_NOMBREABO = "PD_AD_AD_NOMBREABO";
	public final String PD_AD_AD_APELLIDO1ABO = "PD_AD_AD_APELLIDO1ABO";
	public final String PD_AD_AD_APELLIDO2ABO = "PD_AD_AD_APELLIDO2ABO";


     /***** CAMPOS DE LA VISTA V_PCAJG_CONTRARIOS ****/

	public final String C_C_DP_TIPOPERSONA_CDA = "C_C_DP_TIPOPERSONA_CDA";
	public final String C_C_DP_TIPOIDENTIFICACION_CDA = "C_C_DP_TIPOIDENTIFICACION_CDA";
	public final String C_C_DP_IDENTIFICACION = "C_C_DP_IDENTIFICACION";
	public final String C_C_DP_NOMBRE = "C_C_DP_NOMBRE";
	public final String C_C_DP_PRIMERAPELLIDO = "C_C_DP_PRIMERAPELLIDO";
	public final String C_C_DP_SEGUNDOAPELLIDO = "C_C_DP_SEGUNDOAPELLIDO";
	public final String C_C_DP_RAZONSOCIAL = "C_C_DP_RAZONSOCIAL";
	public final String C_C_DP_FECHANACIMIENTO = "C_C_DP_FECHANACIMIENTO";
	public final String C_C_DP_NACIONALIDAD_CDA = "C_C_DP_NACIONALIDAD_CDA";
	public final String C_C_DP_SITUACIONLABORAL_CDA = "C_C_DP_SITUACIONLABORAL_CDA";
	public final String C_C_DP_PROFESION_CDA = "C_C_DP_PROFESION_CDA";
	public final String C_C_DP_SEXO = "C_C_DP_SEXO";
	public final String C_C_DP_IDIOMACOMUNICACION = "C_C_DP_IDIOMACOMUNICACION";
	public final String C_C_DP_ESTADOCIVIL_CDA = "C_C_DP_ESTADOCIVIL_CDA";
	public final String C_C_DP_REGIMENECONOMICO_CDA = "C_C_DP_REGIMENECONOMICO_CDA";
	public final String C_C_DP_NUMHIJOS = "C_C_DP_NUMHIJOS";
	public final String C_C_DP_FECHAFORMALIZACION = "C_C_DP_FECHAFORMALIZACION";
	public final String C_C_DP_TIPOPERSONAJURIDICA_CDA = "C_C_DP_TIPOPERSONAJURIDICA_CDA";
	public final String C_C_DP_COLEGIOPROCURADOR = "C_C_DP_COLEGIOPROCURADOR";
	public final String C_C_DP_NUMCOLEGIADOPROCURADOR = "C_C_DP_NUMCOLEGIADOPROCURADOR";
	public final String C_C_DP_NOMBRECOMPLETOPROCURADO = "C_C_DP_NOMBRECOMPLETOPROCURADO";


     /***** CAMPOS DE LA VISTA V_PCAJG_DOCUMENTACIONEXP_F ****/

	public final String F_F_DE_D_TIPODOCUMENTACION_CDA = "F_F_DE_D_TIPODOCUMENTACION_CDA";
	public final String F_F_DE_D_DD_TIPODOCUMENTO_CDA = "F_F_DE_D_DD_TIPODOCUMENTO_CDA";
	public final String F_F_DE_D_DD_FECHAPRESENTACIDO = "F_F_DE_D_DD_FECHAPRESENTACIDO";
	public final String F_F_DE_D_DD_DESCRIPCIONAMPLIAD = "F_F_DE_D_DD_DESCRIPCIONAMPLIAD";
	public final String F_F_DE_D_DD_PROCEDENTE = "F_F_DE_D_DD_PROCEDENTE";


     /***** CAMPOS DE LA VISTA V_PCAJG_DOCUMENTACIONEXP_DS ****/

	public final String DS_DE_D_TIPODOCUMENTACION_CDA = "DS_DE_D_TIPODOCUMENTACION_CDA";
	public final String DS_DE_D_DD_TIPODOCUMENTO_CDA = "DS_DE_D_DD_TIPODOCUMENTO_CDA";
	public final String DS_DE_D_DD_FECHAPRESENTACIONDO = "DS_DE_D_DD_FECHAPRESENTACIONDO";
	public final String DS_DE_D_DD_DESCRIPCIONAMPLIADA = "DS_DE_D_DD_DESCRIPCIONAMPLIADA";
	public final String DS_DE_D_DD_PROCEDENTE = "DS_DE_D_DD_PROCEDENTE";


     /***** CAMPOS DE LA VISTA V_PCAJG_FAMILIARES ****/

	public final String F_F_PARENTESCO_CDA = "F_F_PARENTESCO_CDA";
	public final String F_F_FAMILIARMENOR = "F_F_FAMILIARMENOR";
	public final String F_F_DP_TIPOPERSONA_CDA = "F_F_DP_TIPOPERSONA_CDA";
	public final String F_F_DP_TIPOIDENTIFICACION_CDA = "F_F_DP_TIPOIDENTIFICACION_CDA";
	public final String F_F_DP_IDENTIFICACION = "F_F_DP_IDENTIFICACION";
	public final String F_F_DP_NOMBRE = "F_F_DP_NOMBRE";
	public final String F_F_DP_PRIMERAPELLIDO = "F_F_DP_PRIMERAPELLIDO";
	public final String F_F_DP_SEGUNDOAPELLIDO = "F_F_DP_SEGUNDOAPELLIDO";
	public final String F_F_DP_RAZONSOCIAL = "F_F_DP_RAZONSOCIAL";
	public final String F_F_DP_FECHANACIMIENTO = "F_F_DP_FECHANACIMIENTO";
	public final String F_F_DP_NACIONALIDAD_CDA = "F_F_DP_NACIONALIDAD_CDA";
	public final String F_F_DP_SITUACIONLABORAL_CDA = "F_F_DP_SITUACIONLABORAL_CDA";
	public final String F_F_DP_PROFESION_CDA = "F_F_DP_PROFESION_CDA";
	public final String F_F_DP_SEXO = "F_F_DP_SEXO";
	public final String F_F_DP_IDIOMACOMUNICACION = "F_F_DP_IDIOMACOMUNICACION";
	public final String F_F_DP_ESTADOCIVIL_CDA = "F_F_DP_ESTADOCIVIL_CDA";
	public final String F_F_DP_REGIMENECONOMICO_CDA = "F_F_DP_REGIMENECONOMICO_CDA";
	public final String F_F_DP_NUMHIJOS = "F_F_DP_NUMHIJOS";
	public final String F_F_DP_FECHAFORMALIZACION = "F_F_DP_FECHAFORMALIZACION";
	public final String F_F_DP_TIPOPERSONAJURIDICA_CDA = "F_F_DP_TIPOPERSONAJURIDICA_CDA";


     /***** CAMPOS DE LA VISTA V_PCAJG_MARCASEXPEDIENTES ****/

	public final String DE_ME_ME_MARCAEXPEDIENTE_CDA = "DE_ME_ME_MARCAEXPEDIENTE_CDA";
	public final String DE_ME_ME_VALORMARCAEXPEDIENTE = "DE_ME_ME_VALORMARCAEXPEDIENTE";


     /***** CAMPOS DE LA VISTA V_PCAJG_DELITOS ****/

	public final String DELITO_CDA = "DELITO_CDA";

}
