package com.siga.ws.i2003.je;

/**
 * NO MODIFICAR. Clase generada con GeneraConstantesXSD
 */

/**
 * @author angelcpe
 *
 */
public interface PCAJGConstantes {

     /***** CAMPOS DE LA VISTA V_WS_JE_2003_DESIGNA ****/

	public final String V_WS_JE_2003_DESIGNA = "V_WS_JE_2003_DESIGNA";

	public final String IDINSTITUCION = "IDINSTITUCION";
	public final String IDFACTURACION = "IDFACTURACION";
	public final String EJG_ANIO = "EJG_ANIO";
	public final String EJG_NUMERO = "EJG_NUMERO";
	public final String DESIGNA_ANIO = "DESIGNA_ANIO";
	public final String DESIGNA_CODIGO = "DESIGNA_CODIGO";
	public final String NUMERO_ACTUACION = "NUMERO_ACTUACION";
	public final String TIPO_REGISTRO_CAB = "TIPO_REGISTRO_CAB";
	public final String CAB1_TIPO_INTERCAMBIO = "CAB1_TIPO_INTERCAMBIO";
	public final String CAB2_NUMERO_INTERCAMBIO = "CAB2_NUMERO_INTERCAMBIO";
	public final String CAB3_ANIO_INTERCAMBIO = "CAB3_ANIO_INTERCAMBIO";
	public final String GRUPO_1 = "GRUPO_1";
	public final String TIPO_REGISTRO_EXP = "TIPO_REGISTRO_EXP";
	public final String AXP1_TIPO_ACTUALIZACION = "AXP1_TIPO_ACTUALIZACION";
	public final String AXP2_NUM_EXPEDIENTE = "AXP2_NUM_EXPEDIENTE";
	public final String AXP3_ANIO_EXPEDIENTE = "AXP3_ANIO_EXPEDIENTE";
	public final String AXP4_NUM_EXP_SERV = "AXP4_NUM_EXP_SERV";
	public final String AXP5_ANIO_EXP_SERV = "AXP5_ANIO_EXP_SERV";
	public final String GRUPO_2 = "GRUPO_2";
	public final String TIPO_REGISTRO_PRJ = "TIPO_REGISTRO_PRJ";
	public final String PRC1_ORGANO_JUDICIAL = "PRC1_ORGANO_JUDICIAL";
	public final String PRC2_TIPO_PROCED_JUDICIAL = "PRC2_TIPO_PROCED_JUDICIAL";
	public final String PRC3_NUM_PROCEDIMIENTO = "PRC3_NUM_PROCEDIMIENTO";
	public final String PRC4_ANIO_PROCEDIMIENTO = "PRC4_ANIO_PROCEDIMIENTO";
	public final String PRC5_NATURALEZA_PROCEDIMIENTO = "PRC5_NATURALEZA_PROCEDIMIENTO";
	public final String PRC6_ESTADO_PROCEDIMIENTO = "PRC6_ESTADO_PROCEDIMIENTO";
	public final String PRC7_RESOLUCION_PROCEDIMIENTO = "PRC7_RESOLUCION_PROCEDIMIENTO";
	public final String PRC8_MOTIVO_MODIFICACION = "PRC8_MOTIVO_MODIFICACION";
	public final String GRUPO_3 = "GRUPO_3";
	public final String TIPO_REGISTRO_PFA = "TIPO_REGISTRO_PFA";
	public final String DPA1_ABOGADO_PROCURADOR = "DPA1_ABOGADO_PROCURADOR";
	public final String DPA2_COLEGIO_PROFESIONAL = "DPA2_COLEGIO_PROFESIONAL";
	public final String DPA3_NCOLEGIADOABOGADO = "DPA3_NCOLEGIADOABOGADO";
	public final String DPA4_FECHA_DESIGNA = "DPA4_FECHA_DESIGNA";
	public final String DPA5_NUMERO_DESIGNA = "DPA5_NUMERO_DESIGNA";
	public final String DPA6_ANIO_DESIGNA = "DPA6_ANIO_DESIGNA";
	public final String GRUPO_4 = "GRUPO_4";
	public final String TIPO_REGISTRO_DAC = "TIPO_REGISTRO_DAC";
	public final String DAC1_TIPO_ACTUACION_SUPLEM = "DAC1_TIPO_ACTUACION_SUPLEM";
	public final String DAC2_FECHA_ACTUACION_SUPLEM = "DAC2_FECHA_ACTUACION_SUPLEM";
	public final String DAC3_NUMERO_SUPLEMENTOS = "DAC3_NUMERO_SUPLEMENTOS";
	public final String DAC4_FECHA_VISITA_PRISION = "DAC4_FECHA_VISITA_PRISION";
	public final String IS_ENVIADO_ENREMESA = "IS_ENVIADO_ENREMESA";
	public final String IS_CAMBIO_JUZGADO = "IS_CAMBIO_JUZGADO";
	public final String IS_CAMBIO_PROCEDIMIENTO = "IS_CAMBIO_PROCEDIMIENTO";

}
