
insert into ECOM_SERVICIO (IDSERVICIO, NOMBRE, ACTIVO, FECHAMODIFICACION, USUMODIFICACION) values (13, 'Facturación', '1', sysdate, 0);
insert into ECOM_OPERACION (IDOPERACION, IDSERVICIO, NOMBRE, MAXREINTENTOS, ACTIVO, FECHAMODIFICACION, USUMODIFICACION) values (61, 13, 'Traspaso facturas Navision - Crear cliente', 1, '1', sysdate, 0);
insert into ECOM_OPERACION (IDOPERACION, IDSERVICIO, NOMBRE, MAXREINTENTOS, ACTIVO, FECHAMODIFICACION, USUMODIFICACION) values (62, 13, 'Traspaso facturas Navision - Crear factura', 1, '1', sysdate, 0);

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadoTraspaso', 'Estado Traspaso', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Finalizado', 'Traspaso Finalizado', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.FinalizadoErrores', 'Traspaso Finalizado con Errores','0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.NoAplica', 'No Aplica Traspaso', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Pendiente', 'Traspaso Pendiente', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Procesando', 'Procesando Traspaso', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Programado', 'Traspaso Programado', '0', '1', to_date('06/06/17','DD/MM/RR'), '0', '19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadoTraspaso', 'Estado Traspaso#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Finalizado', 'Traspaso Finalizado#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.FinalizadoErrores', 'Traspaso Finalizado con Errores#CA','0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.NoAplica', 'No Aplica Traspaso#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Pendiente', 'Traspaso Pendiente#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Procesando', 'Procesando Traspaso#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Programado', 'Traspaso Programado#CA', '0', '2', to_date('06/06/17','DD/MM/RR'), '0', '19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadoTraspaso', 'Estado Traspaso#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Finalizado', 'Traspaso Finalizado#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.FinalizadoErrores', 'Traspaso Finalizado con Errores#EU','0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.NoAplica', 'No Aplica Traspaso#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Pendiente', 'Traspaso Pendiente#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Procesando', 'Procesando Traspaso#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Programado', 'Traspaso Programado#EU', '0', '3', to_date('06/06/17','DD/MM/RR'), '0', '19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadoTraspaso', 'Estado Traspaso#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Finalizado', 'Traspaso Finalizado#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.FinalizadoErrores', 'Traspaso Finalizado con Errores#GL','0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.NoAplica', 'No Aplica Traspaso#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Pendiente', 'Traspaso Pendiente#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Procesando', 'Procesando Traspaso#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.estadosTraspaso.literal.Programado', 'Traspaso Programado#GL', '0', '4', to_date('06/06/17','DD/MM/RR'), '0', '19');


Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('22', null, 'facturacion.estadosTraspaso.literal.NoAplica', 'T', '1', null);
Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('23', null, 'facturacion.estadosTraspaso.literal.Programado', 'T', '1', null);
Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('24', null, 'facturacion.estadosTraspaso.literal.Pendiente', 'T', '1', null);
Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('25', null, 'facturacion.estadosTraspaso.literal.Procesando', 'T', '1', null);
Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('26', null, 'facturacion.estadosTraspaso.literal.Finalizado', 'T', '1', null);
Insert into FAC_ESTADOCONFIRMFACT (IDESTADO, ALIAS, DESCRIPCION, TIPO, LENGUAJE, ORDEN) values ('27', null, 'facturacion.estadosTraspaso.literal.FinalizadoErrores', 'T', '1', null);


Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('general.boton.traspasarFacturas', 'Traspasar Facturas', '0', '1', to_date('07/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('general.boton.traspasarFacturas', 'Traspasar Facturas#CA', '0', '2', to_date('07/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('general.boton.traspasarFacturas', 'Traspasar Facturas#EU', '0', '3', to_date('07/06/17','DD/MM/RR'), '0', '19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('general.boton.traspasarFacturas', 'Traspasar Facturas#GL', '0', '4', to_date('07/06/17','DD/MM/RR'), '0', '19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.generacionFacturacion.literal.confirmarTraspasoFacturas','¿Desea traspasar las facturas?','0','1',to_date('07/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.generacionFacturacion.literal.confirmarTraspasoFacturas','¿Desea traspasar las facturas?#CA','0','2',to_date('07/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.generacionFacturacion.literal.confirmarTraspasoFacturas','¿Desea traspasar las facturas?#EU','0','3',to_date('07/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.generacionFacturacion.literal.confirmarTraspasoFacturas','¿Desea traspasar las facturas?#GL','0','4',to_date('07/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.general.error.ficheroTraspasoFacturas','No existe el fichero de log de traspaso de facturas','0','1',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.general.error.ficheroTraspasoFacturas','No existe el fichero de log de traspaso de facturas#CA','0','2',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.general.error.ficheroTraspasoFacturas','No existe el fichero de log de traspaso de facturas#EU','0','3',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.general.error.ficheroTraspasoFacturas','No existe el fichero de log de traspaso de facturas#GL','0','4',to_date('08/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.envioRealizadoTraspasoFacturas.success','Se ha vuelto a solicitar el traspaso de facturas','0','1',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.envioRealizadoTraspasoFacturas.success','Se ha vuelto a solicitar el traspaso de facturas#CA','0','2',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.envioRealizadoTraspasoFacturas.success','Se ha vuelto a solicitar el traspaso de facturas#EU','0','3',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('messages.envioRealizadoTraspasoFacturas.success','Se ha vuelto a solicitar el traspaso de facturas#GL','0','4',to_date('08/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('modulo.facturacion.traspasoFacturas','Traspasar Facturas','0','1',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('modulo.facturacion.traspasoFacturas','Traspasar Facturas#CA','0','2',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('modulo.facturacion.traspasoFacturas','Traspasar Facturas#EU','0','3',to_date('08/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('modulo.facturacion.traspasoFacturas','Traspasar Facturas#GL','0','4',to_date('08/06/17','DD/MM/RR'),'0','19');

Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_ACTIVO','0', to_date('13/06/17','DD/MM/RR'), '1', '2000', 'ecom.parametro.wstraspasoactivo');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_URL','http://80.91.72.199:7047/DynamicsNAV70/WS/CONSEJO%20TEST%20CONPPTO/Codeunit/WSCGAETEST', to_date('13/06/17','DD/MM/RR'), '1', '2000', 'ecom.parametro.urlwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_PASS','Navision2017WS', to_date('13/06/17','DD/MM/RR'), '1', '2000', 'ecom.parametro.passwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_USER','wsnav', to_date('13/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.userwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_DOMAIN','CGAE', to_date('30/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.domainwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_HOST','80.91.72.199', to_date('30/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.hostwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_PORT','7047', to_date('30/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.portwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_BCC','adrian.ayala@redabogacia.org;jose.barrientos@redabogacia.org;jorge.torres@redabogacia.org', to_date('14/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.mailtraspasobcc');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_FROM','comunicaciones.siga@redabogacia.org', to_date('14/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.mailtraspasofrom');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_ASUNTO','Informe de traspaso de facturas', to_date('14/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.mailtraspasoasunto');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_BODY','Registro de log de Traspaso de Facturas para la serie de facturación %s, programación %s.', to_date('14/06/17','DD/MM/RR'), '0', '2000', 'ecom.parametro.mailtraspasobody');

Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_ACTIVO','0', to_date('13/06/17','DD/MM/RR'), '1', '0', 'ecom.parametro.wstraspasoactivo');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_URL','http://80.91.72.199:7047/DynamicsNAV70/WS/CONSEJO%20TEST%20CONPPTO/Codeunit/WSCGAETEST', to_date('13/06/17','DD/MM/RR'), '1', '0', 'ecom.parametro.urlwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_PASS','Navision2017WS', to_date('13/06/17','DD/MM/RR'), '1', '0', 'ecom.parametro.passwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_USER','wsnav', to_date('13/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.userwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_DOMAIN','CGAE', to_date('30/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.domainwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_HOST','80.91.72.199', to_date('30/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.hostwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_WS_PORT','7047', to_date('30/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.portwstraspaso');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_BCC','adrian.ayala@redabogacia.org;jose.barrientos@redabogacia.org;jorge.torres@redabogacia.org', to_date('14/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.mailtraspasobcc');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_FROM','comunicaciones.siga@redabogacia.org', to_date('14/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.mailtraspasofrom');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_ASUNTO','Informe de traspaso de facturas', to_date('14/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.mailtraspasoasunto');
Insert into GEN_PARAMETROS (MODULO, PARAMETRO, VALOR, FECHAMODIFICACION, USUMODIFICACION, IDINSTITUCION, IDRECURSO) values ('ECOM','TRASPASO_FACTURAS_MAILRESUMEN_BODY','Registro de log de Traspaso de Facturas para la serie de facturación %s, programación %s.', to_date('14/06/17','DD/MM/RR'), '0', '0', 'ecom.parametro.mailtraspasobody');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.urlwstraspaso','Url de acceso al Servicio Web de traspaso de facturas','0','1',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.urlwstraspaso','Url de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.urlwstraspaso','Url de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.urlwstraspaso','Url de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('13/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.userwstraspaso','Usuario de acceso al Servicio Web de traspaso de facturas','0','1',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.userwstraspaso','Usuario de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.userwstraspaso','Usuario de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.userwstraspaso','Usuario de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('13/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.hostwstraspaso','Host de acceso al Servicio Web de traspaso de facturas','0','1',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.hostwstraspaso','Host de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.hostwstraspaso','Host de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.hostwstraspaso','Host de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('30/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.portwstraspaso','Puerto de acceso al Servicio Web de traspaso de facturas','0','1',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.portwstraspaso','Puerto de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.portwstraspaso','Puerto de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.portwstraspaso','Puerto de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('30/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.domainwstraspaso','Dominio de acceso al Servicio Web de traspaso de facturas','0','1',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.domainwstraspaso','Dominio de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.domainwstraspaso','Dominio de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('30/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.domainwstraspaso','Dominio de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('30/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.passwstraspaso','Contraseña de acceso al Servicio Web de traspaso de facturas','0','1',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.passwstraspaso','Contraseña de acceso al Servicio Web de traspaso de facturas#CA','0','2',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.passwstraspaso','Contraseña de acceso al Servicio Web de traspaso de facturas#EU','0','3',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.passwstraspaso','Contraseña de acceso al Servicio Web de traspaso de facturas#GL','0','4',to_date('13/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.wstraspasoactivo','Activar Servicios Web traspaso de facturas(1:Sí, 0:No)','0','1',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.wstraspasoactivo','Activar Servicios Web traspaso de facturas(1:Sí, 0:No)#CA','0','2',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.wstraspasoactivo','Activar Servicios Web traspaso de facturas(1:Sí, 0:No)#EU','0','3',to_date('13/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.wstraspasoactivo','Activar Servicios Web traspaso de facturas(1:Sí, 0:No)#GL','0','4',to_date('13/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobcc','Lista de e-mails separados por punto y coma a los que se envía un correo electrónico cuando se realiza un traspaso de facturas.','0','1',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobcc','Lista de e-mails separados por punto y coma a los que se envía un correo electrónico cuando se realiza un traspaso de facturas.#CA','0','2',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobcc','Lista de e-mails separados por punto y coma a los que se envía un correo electrónico cuando se realiza un traspaso de facturas.#EU','0','3',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobcc','Lista de e-mails separados por punto y coma a los que se envía un correo electrónico cuando se realiza un traspaso de facturas.#GL','0','4',to_date('14/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasofrom','Cuenta de correo electrónico desde donde se envían los correos a los colegios con el traspaso de las facturas.','0','1',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasofrom','Cuenta de correo electrónico desde donde se envían los correos a los colegios con el traspaso de las facturas.#CA','0','2',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasofrom','Cuenta de correo electrónico desde donde se envían los correos a los colegios con el traspaso de las facturas.#EU','0','3',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasofrom','Cuenta de correo electrónico desde donde se envían los correos a los colegios con el traspaso de las facturas.#GL','0','4',to_date('14/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasoasunto','Asunto del correo de traspaso de facturas.','0','1',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasoasunto','Asunto del correo de traspaso de facturas.#CA','0','2',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasoasunto','Asunto del correo de traspaso de facturas.#EU','0','3',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasoasunto','Asunto del correo de traspaso de facturas.#GL','0','4',to_date('14/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobody','Cuerpo del correo de traspaso de facturas.','0','1',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobody','Cuerpo del correo de traspaso de facturas.#CA','0','2',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobody','Cuerpo del correo de traspaso de facturas.#EU','0','3',to_date('14/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('ecom.parametro.mailtraspasobody','Cuerpo del correo de traspaso de facturas.#GL','0','4',to_date('14/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.serios.literal.configuracionTraspasoFacturas','Configuración de traspaso de facturas','0','1',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.serios.literal.configuracionTraspasoFacturas','Configuración de traspaso de facturas#CA','0','2',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.serios.literal.configuracionTraspasoFacturas','Configuración de traspaso de facturas#EU','0','3',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.serios.literal.configuracionTraspasoFacturas','Configuración de traspaso de facturas#GL','0','4',to_date('16/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.traspasarFacturas','Traspasar facturas','0','1',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.traspasarFacturas','Traspasar facturas#CA','0','2',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.traspasarFacturas','Traspasar facturas#EU','0','3',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.traspasarFacturas','Traspasar facturas#GL','0','4',to_date('16/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.plantillaTraspasoFacturas','Plantilla(*)','0','1',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.plantillaTraspasoFacturas','Plantilla(*)#CA','0','2',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.plantillaTraspasoFacturas','Plantilla(*)#EU','0','3',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.datosGenerales.literal.plantillaTraspasoFacturas','Plantilla(*)#GL','0','4',to_date('16/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('envios.plantillas.literal.plantillaTraspasoFacturasAuditoria','Plantilla auditoría(*)','0','1',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('envios.plantillas.literal.plantillaTraspasoFacturasAuditoria','Plantilla auditoría(*)#CA','0','2',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('envios.plantillas.literal.plantillaTraspasoFacturasAuditoria','Plantilla auditoría(*)#EU','0','3',to_date('16/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('envios.plantillas.literal.plantillaTraspasoFacturasAuditoria','Plantilla auditoría(*)#GL','0','4',to_date('16/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaTraspaso','Debe rellenar la plantilla para el traspaso de facturas','0','1',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaTraspaso','Debe rellenar la plantilla para el traspaso de facturas#CA','0','2',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaTraspaso','Debe rellenar la plantilla para el traspaso de facturas#EU','0','3',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaTraspaso','Debe rellenar la plantilla para el traspaso de facturas#GL','0','4',to_date('20/06/17','DD/MM/RR'),'0','19');

Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaAuditoriaTraspaso','Debe rellenar la plantilla de auditoría para el traspaso de facturas','0','1',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaAuditoriaTraspaso','Debe rellenar la plantilla de auditoría para el traspaso de facturas#CA','0','2',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaAuditoriaTraspaso','Debe rellenar la plantilla de auditoría para el traspaso de facturas#EU','0','3',to_date('20/06/17','DD/MM/RR'),'0','19');
Insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('facturacion.mensajes.obligatorio.plantillaAuditoriaTraspaso','Debe rellenar la plantilla de auditoría para el traspaso de facturas#GL','0','4',to_date('20/06/17','DD/MM/RR'),'0','19');

UPDATE FAC_FACTURACIONPROGRAMADA SET IDESTADOTRASPASO='22';


commit;
