create table pys_tipoiva_traspasonav
(
  IDTIPOIVA          NUMBER(5) not null,
  IDINSTITUCION      NUMBER(4) not null,
  FECHAMODIFICACION  DATE not null,
  USUMODIFICACION    NUMBER(5) not null,
  CODIGO_TRASPASONAV VARCHAR2(20) not null
)
tablespace TS_SIGA_FAC;

alter table pys_tipoiva_traspasonav
  add constraint PK_tipoiva_traspasonav primary key (IDTIPOIVA, IDINSTITUCION)
  using index 
  tablespace TS_SIGA_FAC_IDX;
alter table pys_tipoiva_traspasonav
  add constraint FK_pys_tipoiva_traspasonav foreign key (IDTIPOIVA)
  references PYS_TIPOIVA (IDTIPOIVA)
  deferrable;

Insert Into pys_tipoiva_traspasonav(IDTIPOIVA, IDINSTITUCION, FECHAMODIFICACION, USUMODIFICACION, CODIGO_TRASPASONAV)
(Select idtipoiva, 2000, Sysdate, 0, decode(tip.Codigoext, 0, 'EXENTO', tip.Descripciontipo || tip.Codigoext)
   From pys_tipoiva tip
  Where tip.Descripciontipo = 'IVA');

alter table PYS_PRODUCTOSINSTITUCION add CODIGO_TRASPASONAV VARCHAR2(20);
Update Pys_Productosinstitucion Tip
   Set Tip.Codigo_Traspasonav = Decode(Tip.Codigoext, 'NI', 'B010000002', 'NE', 'B010000003', 'CA', 'B010000004')
 Where Tip.Idinstitucion = 2000
   And Tip.Fechabaja Is Null
   And Tip.Tipocertificado = 'C'
   And Tip.Nofacturable = '0';
alter table Pys_Serviciosinstitucion add CODIGO_TRASPASONAV VARCHAR2(20);

ALTER TABLE FAC_SERIEFACTURACION ADD TRASPASO_PLANTILLA VARCHAR2(10);
ALTER TABLE FAC_SERIEFACTURACION ADD TRASPASO_CODAUDITORIA_DEF VARCHAR2(10);
ALTER TABLE FAC_SERIEFACTURACION ADD TRASPASOFACTURAS VARCHAR2(1) DEFAULT '0';
ALTER TABLE FAC_FACTURACIONPROGRAMADA ADD TRASPASO_PLANTILLA VARCHAR2(10);
ALTER TABLE FAC_FACTURACIONPROGRAMADA ADD TRASPASO_CODAUDITORIA_DEF VARCHAR2(10);
ALTER TABLE FAC_FACTURACIONPROGRAMADA ADD TRASPASOFACTURAS VARCHAR2(1) DEFAULT '0';
ALTER TABLE FAC_FACTURA ADD TRASPASADA VARCHAR2(1);
ALTER TABLE FAC_FACTURA ADD ERRORTRASPASO VARCHAR2(4000);
ALTER TABLE FAC_FACTURA ADD ENVIOTRASPASO VARCHAR2(4000);

ALTER TABLE FAC_FACTURACIONPROGRAMADA ADD IDESTADOTRASPASO NUMBER(3) DEFAULT '22';
ALTER TABLE FAC_FACTURACIONPROGRAMADA ADD LOGTRASPASO VARCHAR2(80);
ALTER TABLE FAC_FACTURACIONPROGRAMADA
  ADD CONSTRAINT FK_FAC_ESTADOCONFIRM_TRAS FOREIGN KEY (IDESTADOTRASPASO)
  REFERENCES FAC_ESTADOCONFIRMFACT (IDESTADO)
  deferrable;
