insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoOk', 'Expedientes cuya información económica ha sido enviada sin incidencias', 0, '1', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoOk', 'Expedientes cuya información económica ha sido enviada sin incidencias#CA', 0, '2', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoOk', 'Expedientes cuya información económica ha sido enviada sin incidencias#EU', 0, '3', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoOk', 'Expedientes cuya información económica ha sido enviada sin incidencias#GL', 0, '4', sysdate, 0, '19');

insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoSol', 'Expedientes a los que se ha solicidado el envio del informe econÃ³mico', 0, '1', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoSol', 'Expedientes a los que se ha solicidado el envio del informe económico#CA', 0, '2', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoSol', 'Expedientes a los que se ha solicidado el envio del informe económico#EU', 0, '3', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoSol', 'Expedientes a los que se ha solicidado el envio del informe económico#GL', 0, '4', sysdate, 0, '19');

insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoKo', 'Expedientes cuya información económica ha sido enviada con incidencias', 0, '1', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoKo', 'Expedientes cuya información económica ha sido enviada con incidencias#CA', 0, '2', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoKo', 'Expedientes cuya información económica ha sido enviada con incidencias#EU', 0, '3', sysdate, 0, '19');
insert into GEN_RECURSOS (IDRECURSO, DESCRIPCION, ERROR, IDLENGUAJE, FECHAMODIFICACION, USUMODIFICACION, IDPROPIEDAD) values ('cajg.opcion.informeEconomicoKo', 'Expedientes cuya información económica ha sido enviada con incidencias#GL', 0, '4', sysdate, 0, '19');