CREATE OR REPLACE VIEW V_PCAJG_DOCUMENTACIONEXP_DS AS
SELECT IDINSTITUCION
      , IDTIPOEJG
      , ANIO
      , NUMERO
      , IDREMESA
      , IDPERSONA
      , IDLENGUAJE
      , TIPODOCUMENTACION_CDA AS DS_DE_D_TIPODOCUMENTACION_CDA
      , TIPODOCUMENTO_CDA AS DS_DE_D_DD_TIPODOCUMENTO_CDA
      , FECHAPRESENTACIONDO AS DS_DE_D_DD_FECHAPRESENTACIONDO
      , DESCRIPCIONAMPLIADA AS DS_DE_D_DD_DESCRIPCIONAMPLIADA
      , PROCEDENTE AS DS_DE_D_DD_PROCEDENTE
      , NOMBRE_ARCHIVO AS DS_DE_D_DD_NOMBRE_ARCHIVO
      , EXTENSION_ARCHIVO AS DS_DE_D_DD_EXTENSION_ARCHIVO
      , DIRECTORIO_ARCHIVO AS DS_DE_D_DD_DIRECTORIO_ARCHIVO
FROM V_PCAJG_M_DOCUMENTACIONEXP
WHERE 1 = 0;
 
