CREATE OR REPLACE VIEW V_PCAJG_EJG AS
SELECT EJGREMESA.IDREMESA
      , EJGREMESA.IDINSTITUCION
      , EJG.IDTIPOEJG
      , EJG.ANIO
      , EJG.NUMERO
      , EJG.NUMEJG
      , LEN.IDLENGUAJE
      , EJGREMESA.IDEJGREMESA
      , (CASE
        WHEN I.CEN_INST_IDINSTITUCION IN (3003, 3004,3009)
        THEN '01'
              WHEN (((SELECT COUNT(1) --SI TIENE UN CAMBIO DE LETRADO
                      FROM SCS_DESIGNASLETRADO DL, SCS_EJGDESIGNA ED
                      WHERE DL.IDINSTITUCION = ED.IDINSTITUCION
                      AND DL.IDTURNO = ED.IDTURNO
                      AND DL.ANIO = ED.ANIODESIGNA
                      AND DL.NUMERO = ED.NUMERODESIGNA
                      AND ED.IDINSTITUCION = EJG.IDINSTITUCION
                      AND ED.IDTIPOEJG = EJG.IDTIPOEJG
                      AND ED.ANIOEJG = EJG.ANIO
                      AND ED.NUMEROEJG = EJG.NUMERO
                      AND ED.ANIODESIGNA || LPAD(ED.NUMERODESIGNA, 10, '0') = --ULTIMA DESIGNA
                       (SELECT MAX(ED2.ANIODESIGNA || LPAD(ED2.NUMERODESIGNA, 10, '0'))
                               FROM SCS_EJGDESIGNA ED2
                               WHERE ED2.IDINSTITUCION = EJG.IDINSTITUCION
                               AND ED2.IDTIPOEJG = EJG.IDTIPOEJG
                               AND ED2.ANIOEJG = EJG.ANIO
                               AND ED2.NUMEROEJG = EJG.NUMERO)
                      GROUP BY DL.NUMERO) > 1)
                    AND ((SELECT COUNT(1) -- Y SE HA ENVIADO EN OTRA REMESA
                      FROM CAJG_EJGREMESA ER, CAJG_REMESAESTADOS RE
                      WHERE ER.IDINSTITUCION = RE.IDINSTITUCION
                      AND ER.IDREMESA = RE.IDREMESA
                      AND ER.IDINSTITUCION = EJG.IDINSTITUCION
                      AND ER.ANIO = EJG.ANIO
                      AND ER.NUMERO = EJG.NUMERO
                      AND ER.IDTIPOEJG = EJG.IDTIPOEJG
                      AND ER.IDREMESA <> EJGREMESA.IDREMESA --OTRA REMESA
                      AND RE.IDESTADO > 1--2=ENVIADA
                      AND ER.IDEJGREMESA NOT IN (SELECT RESEJG.IDEJGREMESA FROM CAJG_RESPUESTA_EJGREMESA RESEJG)--ENVIADA SIN ERRORES
                      AND RE.IDESTADO = (SELECT MAX(IDESTADO)
                      FROM CAJG_REMESAESTADOS RE2
                      WHERE RE.IDINSTITUCION = RE2.IDINSTITUCION
                      AND RE.IDREMESA = RE2.IDREMESA)) > 0))
              THEN 'ICD' --INTERCAMBIO CAMBIO DESIGNACION
              WHEN ((SELECT COUNT(1) --VER SI TIENE EL ESTADO ARCHIVADO
                   FROM SCS_ESTADOEJG EE
                   WHERE EE.IDINSTITUCION = EJG.IDINSTITUCION
                   AND EE.ANIO = EJG.ANIO
                   AND EE.IDTIPOEJG = EJG.IDTIPOEJG
                   AND EE.NUMERO = EJG.NUMERO
                   and EE.fechabaja is null
                   AND EE.IDESTADOEJG = 12) > 0)--ARCHIVADO
              THEN 'IEA' --INTERCAMBIO EXPEDIENTES ARCHIVADOS
              ELSE 'IED' --INTERCAMBIO EXPEDIENTES DICTAMINADOS
              --ELSE 'IAP' --INTERCAMBIO ALTA PRESENTACION
              END) AS TIPOINTERCAMBIO
       , (CASE
               WHEN I.CEN_INST_IDINSTITUCION = 3001
               THEN TO_CHAR(I.IDINSTITUCION)
         WHEN I.IDINSTITUCION = 2010
         THEN TO_CHAR(I.IDINSTITUCION)
               ELSE I.CODIGOEXT || '##' || I.NOMBRE
               END) AS ORIGENINTERCAMBIO_CDA
       , DECODE (I.CEN_INST_IDINSTITUCION,3009,'20##SIGA','SG##SIGA') AS ORIGENSISTEMA_CDA
        , (CASE
               WHEN I.CEN_INST_IDINSTITUCION IN (3004,3009)
               THEN (SELECT I.IDCOMISION FROM CEN_INSTITUCION I WHERE I.IDINSTITUCION = EJGREMESA.IDINSTITUCION)
               ELSE 'GEN'
               END) AS DESTINOINTERCAMBIO_CDA
       , EJGREMESA.IDREMESA AS IDINTERCAMBIO_PCAJG
       , (CASE
               WHEN EJG.IDINSTITUCION = 2083--zaragoza
               THEN TO_CHAR(EJGREMESA.IDREMESA) || '1'
               WHEN EJG.IDINSTITUCION = 2034--huesca
               THEN TO_CHAR(EJGREMESA.IDREMESA) || '2'
               WHEN EJG.IDINSTITUCION = 2073--teruel
               THEN TO_CHAR(EJGREMESA.IDREMESA) || '3'
               WHEN I.CEN_INST_IDINSTITUCION IN (3003, 3004,3009)
               THEN TO_CHAR(SYSDATE, 'DDMMYYYYHH24MISS')
               ELSE
                    (SELECT TO_CHAR(NVL(MAX(R.IDINTERCAMBIO), 0) + 1) FROM CAJG_REMESA R WHERE R.IDINSTITUCION = EJGREMESA.IDINSTITUCION AND R.IDREMESA <> EJGREMESA.IDREMESA)
               END) AS IDENTIFICADORINTERCAMBIO
       , (CASE I.CEN_INST_IDINSTITUCION
               WHEN 3004 THEN TO_CHAR(SYSDATE, 'DDMMYYYY')
               ELSE TO_CHAR(SYSDATE, 'DD-MM-YYYY')
               END) AS FECHA_INTERCAMBIO
       , '2.5.2' AS VERSION_PCAJG
       , '3.1.1' AS VERSION_XSD_GENERALITAT
       , 'yyyy-MM-dd' AS FORMATO_FECHAS
      --Datos Expedientes
      , (CASE WHEN I.CEN_INST_IDINSTITUCION = 3001
              THEN (SELECT T.CODIGOEXT FROM SCS_TIPOEJGCOLEGIO T
                    WHERE T.IDINSTITUCION = EJG.IDINSTITUCION AND T.IDTIPOEJGCOLEGIO = 1)
              ELSE (SELECT T.CODIGOEXT FROM SCS_TIPOEJGCOLEGIO T
                    WHERE T.IDINSTITUCION = EJG.IDINSTITUCION AND T.IDTIPOEJGCOLEGIO = EJG.IDTIPOEJGCOLEGIO)
              END) AS DE_CE_COLEGIOEXPEDIENTE
      , EJG.NUMEJG AS DE_CE_NUMEXPEDIENTE
      , EJG.ANIO AS DE_CE_ANYOEXPEDIENTE
      , NULL AS DE_CES_ORIGENEXPEDIENTESERVICI --en el envío de expedientes desde SIGA no se usan estos campos (ver mail 06-03-2012)
      , NULL AS DE_CES_NUMEXPEDIENTESERVICIO
      , NULL AS DE_CES_ANYOEXPEDIENTESERVICIO
      , EJG.FECHAAPERTURA AS DE_FECHASOLICITUD
      , EJG.OBSERVACIONES AS DE_OBSERVACIONES2
      , (SELECT COUNT(1) FROM SCS_UNIDADFAMILIAREJG UFF
                WHERE UFF.IDINSTITUCION = UF.IDINSTITUCION
                AND UFF.ANIO = UF.ANIO
                AND UFF.IDTIPOEJG = UF.IDTIPOEJG
                AND UFF.NUMERO = UF.NUMERO
                AND UFF.IDPERSONA <> UF.IDPERSONA
                AND UFF.IDPARENTESCO IN (1, 3, 4)) AS DE_CANTIDAD_MIEMBROS_UF
      --Profesionales Designados
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN DECODE(VPROC.FECHARENUNCIASOLICITA, NULL, 0, 1)
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN DECODE(PROC.FECHABAJA, NULL, 0, 1)
              ELSE NULL
              END) AS PD_PD_BAJAPROCURADORDESIGNADO
      , (CASE
             WHEN EJG.IDINSTITUCION = 2064 AND (VPROC.IDPROCURADOR IS NOT NULL OR PROC.IDPROCURADOR IS NOT NULL)--SANTIAGO
             THEN '0'
             WHEN EJG.IDINSTITUCION = 2025 AND (VPROC.IDPROCURADOR IS NOT NULL OR PROC.IDPROCURADOR IS NOT NULL)--FERROL
             THEN '1'
             WHEN EJG.IDINSTITUCION = 2044 AND (VPROC.IDPROCURADOR IS NOT NULL OR PROC.IDPROCURADOR IS NOT NULL)--LUGO
             THEN '2'
             WHEN EJG.IDINSTITUCION = 2052 AND (VPROC.IDPROCURADOR IS NOT NULL OR PROC.IDPROCURADOR IS NOT NULL)--OURENSE
             THEN '3'
             WHEN I.CEN_INST_IDINSTITUCION = 3001--CATALANES
             THEN DECODE(NVL(VPROC.COD_COL_PROCURADOR, PROC.IDCOLPROCURADOR), 'P08019', 'PBAR', 'P08113', 'PMAN', 'P08121', 'PMAT'
                                                       , 'P08279', 'PTER', 'P17079', 'PGIR', 'P25120', 'PLLE', 'P43123', 'PREU', 'P43155', 'PTOR', 'P43148', 'PTAR', NULL)
             WHEN VPROC.IDPROCURADOR IS NOT NULL
             THEN VPROC.COD_COL_PROCURADOR
             WHEN PROC.IDPROCURADOR IS NOT NULL
             THEN PROC.IDCOLPROCURADOR
             ELSE NULL
             END) AS PD_PD_DP_COLEGIOPROCURADOR
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.COD_COL_PROCURADOR
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.IDCOLPROCURADOR
              ELSE NULL
              END) AS PD_PD_DP_COLPROCURADOR_EJIS
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.NCOLEGIADO
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.NCOLEGIADO
              ELSE NULL
              END) AS PD_PD_DP_NUMCOLEGIADOPROCURADO
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.NOMBRE || ' ' || VPROC.APELLIDOS1 ||  ' ' || VPROC.APELLIDOS2
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.NOMBRE || ' ' || PROC.APELLIDOS1 ||  ' ' || PROC.APELLIDOS2
              ELSE NULL
              END) AS PD_PD_DP_NOMBRECOMPLETOPROCURA
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.FECHADESIGNA
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN EJG.FECHA_DES_PROC
              ELSE NULL
              END) AS PD_PD_FECHADESIGNACIONPROCURAD
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.NUMERODESIGNACION
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN EJG.NUMERODESIGNAPROC
              ELSE NULL
              END) AS PD_PD_NUMDESIGNACIONPROCURADOR
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.NOMBRE
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.NOMBRE
              ELSE NULL
              END) AS PD_PD_DP_NOMBRE
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.APELLIDOS1
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.APELLIDOS1
              ELSE NULL
              END) AS PD_PD_DP_APELLIDO1
      , (CASE WHEN VPROC.IDPROCURADOR IS NOT NULL
              THEN VPROC.APELLIDOS2
              WHEN PROC.IDPROCURADOR IS NOT NULL
              THEN PROC.APELLIDOS2
              ELSE NULL
              END) AS PD_PD_DP_APELLIDO2
      , NULL AS PD_PD_DP_NIF
      --Datos Solicitante
      , VDP.IDPERSONA
      , VDP.TIPOPERSONA_CDA AS DS_DP_TIPOPERSONA_CDA
      , VDP.TIPOIDENTIFICACION_CDA AS DS_DP_TIPOIDENTIFICACION_CDA
      , VDP.TIPOIDENTIFICACION_EJIS AS DS_DP_TIPOIDENTIFICACION_EJIS
      , VDP.IDENTIFICACION AS DS_DP_IDENTIFICACION
      , VDP.NOMBRE AS DS_DP_NOMBRE
      , VDP.PRIMERAPELLIDO AS DS_DP_PRIMERAPELLIDO
      , VDP.SEGUNDOAPELLIDO AS DS_DP_SEGUNDOAPELLIDO
      , VDP.RAZONSOCIAL AS DS_DP_RAZONSOCIAL
      , VDP.FECHANACIMIENTO AS DS_DP_FECHANACIMIENTO
      , VDP.NACIONALIDAD_CDA AS DS_DP_NACIONALIDAD_CDA
      , (SELECT GL.CODIGOEXT || '##' || F_SIGA_GETRECURSO(GL.DESCRIPCION, LEN.IDLENGUAJE)
             FROM SCS_UNIDADFAMILIAREJG UF, SCS_TIPOGRUPOLABORAL GL
             WHERE GL.IDTIPOGRUPOLAB = UF.IDTIPOGRUPOLAB
              AND GL.IDINSTITUCION = UF.IDINSTITUCION
              AND EJG.IDINSTITUCION = UF.IDINSTITUCION
              AND EJG.IDPERSONA = UF.IDPERSONA
              AND UF.IDINSTITUCION = EJG.IDINSTITUCION
              AND UF.ANIO = EJG.ANIO
              AND UF.NUMERO = EJG.NUMERO
              AND UF.IDTIPOEJG = EJG.IDTIPOEJG) AS DS_DP_SITUACIONLABORAL_CDA
      , VDP.PROFESION_CDA AS DS_DP_PROFESION_CDA
      , VDP.SEXO AS DS_DP_SEXO
      , VDP.SEXO_EJIS AS DS_DP_SEXO_EJIS
      , VDP.IDIOMACOMUNICACION AS DS_DP_IDIOMACOMUNICACION
      , VDP.ESTADOCIVIL_CDA AS DS_DP_ESTADOCIVIL_CDA
    , VDP.ESTADOCIVIL_EJIS AS DS_DP_ESTADOCIVIL_EJIS
      , VDP.REGIMENECONOMICO_CDA AS DS_DP_REGIMENECONOMICO_CDA
      , VDP.REGIMENECONOMICO_EJIS AS DS_DP_REGIMENECONOMICO_EJIS
      , VDP.NUMHIJOS AS DS_DP_NUMHIJOS
      , VDP.FECHAFORMALIZACION AS DS_DP_FECHAFORMALIZACION
      , VDP.TIPOPERSONAJURIDICA_CDA AS DS_DP_TIPOPERSONAJURIDICA_CDA
      , VDP.TIPODOMICILIO_CDA AS DS_DP_TIPODOMICILIO_CDA
      , VDP.TIPODOMICILIO_EJIS AS DS_DP_TIPODOMICILIO_EJIS
      , VDP.TIPOVIA_CDA AS DS_DP_DD_TIPOVIA_CDA
      , VDP.NOMBREVIA AS DS_DP_DD_NOMBREVIA
      , VDP.NUMERODIRECCION AS DS_DP_DD_NUMERODIRECCION
      , VDP.ESCALERADIRECCION AS DS_DP_DD_ESCALERADIRECCION
      , VDP.PISODIRECCION AS DS_DP_DD_PISODIRECCION
      , VDP.PUERTADIRECCION AS DS_DP_DD_PUERTADIRECCION
      , VDP.PAIS_CDA AS DS_DP_DD_PAIS_CDA
      , VDP.PROVINCIA_CDA AS DS_DP_DD_PROVINCIA_CDA
      , VDP.MUNICIPIO_CDA AS DS_DP_DD_M_MUNICIPIO_CDA
    , VDP.MUNICIPIO_EJIS AS DS_DP_DD_M_MUNICIPIO_EJIS
      , VDP.SUBCODIGOMUNICIPIO AS DS_DP_DD_M_SUBCODIGOMUNICIPIO
      , VDP.CODIGOPOSTAL AS DS_DP_DD_CODIGOPOSTAL
      , VDP.NUMEROTELEFONO1 AS DS_DC_NUMEROTELEFONO1
      , VDP.NUMEROTELEFONO2 AS DS_DC_NUMEROTELEFONO2
      , VDP.EMAIL AS DS_DC_EMAIL
      , nvl(VDP.AUTORIZAAVISOTELEMATICO,0) AS DS_DC_AVISOTELEMATICO
          --Documentacion Expediente (Ver V_PCAJG_DOCUMENTACIONEXP_DS)
          ,  DECODE(I. CEN_INST_IDINSTITUCION,3009,(CASE WHEN UF.DESCRIPCIONINGRESOSANUALES IS NOT NULL
                       OR UF.IMPORTEINGRESOSANUALES IS NOT NULL
                  THEN 'INAN##Ingresos anuales'
                  ELSE NULL END),(CASE WHEN UF.DESCRIPCIONINGRESOSANUALES IS NOT NULL
                       OR UF.IMPORTEINGRESOSANUALES IS NOT NULL
                  THEN 'ALT##Ingresos anuales'
                  ELSE NULL END) ) AS DS_DEP_I_CONCEPTOINGRESOS_CDA
          , UF.DESCRIPCIONINGRESOSANUALES AS DS_DEP_I_OBSERVACIONESINGRESOS
          , NULL AS DS_DEP_I_DESCRIPCIONINGRESOS
          , UF.IMPORTEINGRESOSANUALES AS DS_DEP_I_IMPORTEBRUTO
          , NULL AS DS_DEP_I_ACUMULABLE
          , NULL AS DS_DEP_PBI_TIPOBIENINMUEBL_CDA
          , NULL AS DS_DEP_PBI_ORIGENVALORACIO_CDA
          , NULL AS DS_DEP_PBI_CARGAS
          , NULL AS DS_DEP_PBI_OBSERVACIONES --UF.BIENESINMUEBLES
          , NULL AS DS_DEP_PBI_VALORACIONECONOMICA --UF.IMPORTEBIENESINMUEBLES
          , NULL AS DS_DEP_PBI_ACUMULABLE
          , NULL AS DS_DEP_PBM_TIPOBIENMUEBLE_CDA
          , NULL AS DS_DEP_PBM_OBSERVACIONES --UF.BIENESMUEBLES
          , NULL AS DS_DEP_PBM_VALORACIONECONOMICA --UF.IMPORTEBIENESMUEBLES
          , NULL AS DS_DEP_PBM_ACUMULABLE
          , NULL AS DS_DEP_PBO_CARGAS
          , NULL AS DS_DEP_PBO_DESCRIPCIONBIEN
          , NULL AS DS_DEP_PBO_OBSERVACIONES --UF.OTROSBIENES
          , NULL AS DS_DEP_PBO_VALORACIONECONOMICA --UF.IMPORTEOTROSBIENES
          , NULL AS DS_DEP_PBO_ACUMULABLE
          , NULL AS DS_DEP_OTROSDATOSECONOMICOS
      , (SELECT DECODE(COUNT(1), 0, NULL, 1)
                FROM SCS_EEJG_PETICIONES PET
                WHERE PET.IDINSTITUCION = UF.IDINSTITUCION
                AND PET.ANIO = UF.ANIO
                AND PET.NUMERO = UF.NUMERO
                AND PET.IDTIPOEJG = UF.IDTIPOEJG
                AND PET.IDPERSONA = UF.IDPERSONA) AS DS_DEP_CONSENTIMIENTO_DATOS
      --Datos Representante
      , VDP_REP.TIPOPERSONA_CDA AS DR_DP_TIPOPERSONA_CDA
      , VDP_REP.TIPOIDENTIFICACION_CDA AS DR_DP_TIPOIDENTIFICACION_CDA
      , VDP_REP.TIPOIDENTIFICACION_EJIS AS DR_DP_TIPOIDENTIFICACION_EJIS
      , VDP_REP.IDENTIFICACION AS DR_DP_IDENTIFICACION
      , VDP_REP.NOMBRE AS DR_DP_NOMBRE
      , VDP_REP.PRIMERAPELLIDO AS DR_DP_PRIMERAPELLIDO
      , VDP_REP.SEGUNDOAPELLIDO AS DR_DP_SEGUNDOAPELLIDO
      , VDP_REP.RAZONSOCIAL AS DR_DP_RAZONSOCIAL
      , VDP_REP.FECHANACIMIENTO AS DR_DP_FECHANACIMIENTO
      , VDP_REP.NACIONALIDAD_CDA AS DR_DP_NACIONALIDAD_CDA
      , NULL AS DR_DP_SITUACIONLABORAL_CDA -- NO HAY INFORMACION EN SIGA
      , VDP_REP.PROFESION_CDA AS DR_DP_PROFESION_CDA
      , VDP_REP.SEXO AS DR_DP_SEXO
      , VDP_REP.SEXO_EJIS AS DR_DP_SEXO_EJIS
      , VDP_REP.IDIOMACOMUNICACION AS DR_DP_IDIOMACOMUNICACION
      , VDP_REP.ESTADOCIVIL_CDA AS DR_DP_ESTADOCIVIL_CDA
    , VDP_REP.ESTADOCIVIL_EJIS AS DR_DP_ESTADOCIVIL_EJIS
      , VDP_REP.REGIMENECONOMICO_CDA AS DR_DP_REGIMENECONOMICO_CDA
      , VDP_REP.REGIMENECONOMICO_EJIS AS DR_DP_REGIMENECONOMICO_EJIS
      , VDP_REP.NUMHIJOS AS DR_DP_NUMHIJOS
      , VDP_REP.FECHAFORMALIZACION AS DR_DP_FECHAFORMALIZACION
      , VDP_REP.TIPOPERSONAJURIDICA_CDA AS DR_DP_TIPOPERSONAJURIDICA_CDA
      , VDP_REP.TIPODOMICILIO_CDA AS DR_DP_TIPODOMICILIO_CDA
      , VDP_REP.TIPODOMICILIO_EJIS AS DR_DP_TIPODOMICILIO_EJIS
      , VDP_REP.TIPOVIA_CDA AS DR_DP_DD_TIPOVIA_CDA
      , VDP_REP.NOMBREVIA AS DR_DP_DD_NOMBREVIA
      , VDP_REP.NUMERODIRECCION AS DR_DP_DD_NUMERODIRECCION
      , VDP_REP.ESCALERADIRECCION AS DR_DP_DD_ESCALERADIRECCION
      , VDP_REP.PISODIRECCION AS DR_DP_DD_PISODIRECCION
      , VDP_REP.PUERTADIRECCION AS DR_DP_DD_PUERTADIRECCION
      , VDP_REP.PAIS_CDA AS DR_DP_DD_PAIS_CDA
      , VDP_REP.PROVINCIA_CDA AS DR_DP_DD_PROVINCIA_CDA
      , VDP_REP.MUNICIPIO_CDA AS DR_DP_DD_M_MUNICIPIO_CDA
    , VDP_REP.MUNICIPIO_EJIS AS DR_DP_DD_M_MUNICIPIO_EJIS
      , VDP_REP.SUBCODIGOMUNICIPIO AS DR_DP_DD_M_SUBCODIGOMUNICIPIO
      , VDP_REP.CODIGOPOSTAL AS DR_DP_DD_CODIGOPOSTAL
      , VDP_REP.NUMEROTELEFONO1 AS DR_DC_NUMEROTELEFONO1
      , VDP_REP.NUMEROTELEFONO2 AS DR_DC_NUMEROTELEFONO2
      , VDP_REP.EMAIL AS DR_DC_EMAIL
      , nvl(VDP_REP.AUTORIZAAVISOTELEMATICO,0) AS DR_DC_AVISOTELEMATICO
      --Familiares (VER V_PCAJG_FAMILIARES)
      --Contrarios (VER V_PCAJG_CONTRARIOS)
      --Datos Defensa Judicial
      --, DECODE(PJ.IDPARTIDO, NULL, '-1##Indeterminado', PJ.CODIGOEXT || '##' || PJ.NOMBRE) AS DDJ_PARTIDOJUDICIAL_CDA --Confirmado por asoler
      , (CASE
              WHEN
                D.IDJUZGADO IS NOT NULL AND  I.CEN_INST_IDINSTITUCION IN (3003, 3010)
              THEN
                (SELECT LPAD(PJ.IDPARTIDO, 4, '0') || '##' || PJ.NOMBRE
                FROM CEN_PARTIDOJUDICIAL PJ, CEN_POBLACIONES POB, SCS_JUZGADO J
                WHERE J.IDINSTITUCION = D.IDINSTITUCION_JUZG
                AND J.IDJUZGADO = D.IDJUZGADO
                AND J.IDPOBLACION = POB.IDPOBLACION
                AND POB.IDPARTIDO = PJ.IDPARTIDO)
              WHEN
                D.IDJUZGADO IS NOT NULL AND  I.CEN_INST_IDINSTITUCION NOT IN (3003, 3010)
              THEN
               (SELECT PJ.CODIGOEXT || '##' || PJ.NOMBRE
                FROM CEN_PARTIDOJUDICIAL PJ, CEN_POBLACIONES POB, SCS_JUZGADO J
                WHERE J.IDINSTITUCION = D.IDINSTITUCION_JUZG
                AND J.IDJUZGADO = D.IDJUZGADO
                AND J.IDPOBLACION = POB.IDPOBLACION
                AND POB.IDPARTIDO = PJ.IDPARTIDO)
              WHEN
                EJG.JUZGADO IS NOT NULL AND  I.CEN_INST_IDINSTITUCION IN (3003, 3010)
              THEN
                (SELECT LPAD(PJ.IDPARTIDO, 4, '0') || '##' || PJ.NOMBRE
                FROM CEN_PARTIDOJUDICIAL PJ, CEN_POBLACIONES POB, SCS_JUZGADO J
                WHERE J.IDINSTITUCION = EJG.JUZGADOIDINSTITUCION
                AND J.IDJUZGADO = EJG.JUZGADO
                AND J.IDPOBLACION = POB.IDPOBLACION
                AND POB.IDPARTIDO = PJ.IDPARTIDO)
               WHEN
                EJG.JUZGADO IS NOT NULL AND  I.CEN_INST_IDINSTITUCION NOT IN (3003, 3010)
              THEN
                (SELECT  PJ.CODIGOEXT || '##' || PJ.NOMBRE
                FROM CEN_PARTIDOJUDICIAL PJ, CEN_POBLACIONES POB, SCS_JUZGADO J
                WHERE J.IDINSTITUCION = EJG.JUZGADOIDINSTITUCION
                AND J.IDJUZGADO = EJG.JUZGADO
                AND J.IDPOBLACION = POB.IDPOBLACION
                AND POB.IDPARTIDO = PJ.IDPARTIDO)
        WHEN
        I.CEN_INST_IDINSTITUCION IN (3001, 3010,3009)
              THEN
                DECODE(LEN.IDLENGUAJE, 2, '-1##Indeterminat', '-1##Indeterminado')
        ELSE
        NULL
              END) AS DDJ_PARTIDOJUDICIAL_CDA
      , (CASE
             WHEN JUR_D.IDJURISDICCION IS NOT NULL
             THEN (SELECT P.CODIGO || '##' || P.DESCRIPCION
                          FROM PCAJG_JURISDICCION P, PCAJG_JURIS_SCS_JURIS PS --CAMBIO 20100527
                          WHERE P.IDENTIFICADOR = PS.IDENTIFICADOR
                           AND P.IDINSTITUCION = PS.IDINSTITUCION
                           AND P.IDINSTITUCION = EJG.IDINSTITUCION
                           AND PS.IDJURISDICCION = JUR_D.IDJURISDICCION)
             WHEN JUR.IDJURISDICCION IS NOT NULL
             THEN (SELECT P.CODIGO || '##' || P.DESCRIPCION
                          FROM PCAJG_JURISDICCION P, PCAJG_JURIS_SCS_JURIS PS --CAMBIO 20100527
                          WHERE P.IDENTIFICADOR = PS.IDENTIFICADOR
                           AND P.IDINSTITUCION = PS.IDINSTITUCION
                           AND P.IDINSTITUCION = EJG.IDINSTITUCION
                           AND PS.IDJURISDICCION = JUR.IDJURISDICCION)
             ELSE DECODE(LEN.IDLENGUAJE, 2, '-1##Indeterminat', '-1##Indeterminado') END) AS DDJ_JURISDICCION_CDA
       , (CASE WHEN JUR_D.IDJURISDICCION IS NOT NULL
               THEN JUR_D.CODIGOEJIS
               WHEN JUR.IDJURISDICCION IS NOT NULL
               THEN JUR.CODIGOEJIS
               ELSE NULL END) AS DDJ_JURISDICCION_EJIS
       , (CASE
             WHEN D.IDJUZGADO IS NOT NULL
             THEN (SELECT J.ESDECANO
                  FROM SCS_JUZGADO J
                  WHERE J.IDINSTITUCION = D.IDINSTITUCION_JUZG
                  AND J.IDJUZGADO = D.IDJUZGADO)
             WHEN EJG.JUZGADO IS NOT NULL
             THEN (SELECT J.ESDECANO
                  FROM SCS_JUZGADO J
                  WHERE J.IDINSTITUCION = EJG.JUZGADOIDINSTITUCION
                  AND J.IDJUZGADO = EJG.JUZGADO)
             ELSE NULL END) AS DDJ_ORGANOJUDICIAL_ESDECANO
      , (CASE
             WHEN D.IDJUZGADO IS NOT NULL
             THEN (SELECT (CASE
              WHEN I.CEN_INST_IDINSTITUCION IN (3001, 3010)
              THEN J.CODIGOEXT
              ELSE J.CODIGOEJIS END) || '##' || J.NOMBRE
                  FROM SCS_JUZGADO J
                  WHERE J.IDINSTITUCION = D.IDINSTITUCION_JUZG
                  AND J.IDJUZGADO = D.IDJUZGADO)
             WHEN EJG.JUZGADO IS NOT NULL
             THEN (SELECT (CASE
              WHEN I.CEN_INST_IDINSTITUCION IN (3001, 3010)
              THEN J.CODIGOEXT
              ELSE J.CODIGOEJIS END) || '##' || J.NOMBRE
                  FROM SCS_JUZGADO J
                  WHERE J.IDINSTITUCION = EJG.JUZGADOIDINSTITUCION
                  AND J.IDJUZGADO = EJG.JUZGADO)
             ELSE NULL END) AS DDJ_ORGANOJUDICIAL_CDA
      , (CASE
              WHEN PRE_D.IDPRETENSION IS NOT NULL
              THEN PRE_D.CODIGOEXT || '##' || SUBSTR(F_SIGA_GETRECURSO(PRE_D.DESCRIPCION, LEN.IDLENGUAJE), 1, 50)
              WHEN PRE.IDPRETENSION IS NOT NULL
              THEN PRE.CODIGOEXT || '##' || SUBSTR(F_SIGA_GETRECURSO(PRE.DESCRIPCION, LEN.IDLENGUAJE), 1, 50)
              ELSE NULL END) AS DDJ_TIPOPROCEDIMIENTO_CDA
      , DECODE(D.IDJUZGADO, NULL, TRIM(EJG.NUMEROPROCEDIMIENTO), TRIM(D.NUMPROCEDIMIENTO)) AS DDJ_IDENTIFICADORPROCEDIMIENTO
      , EJG.OBSERVACIONES AS DDJ_RESUMENPRETENSION --Confirmado por asoler
      , DECODE(EJG.IDRENUNCIA, 2, 1, NULL, NULL, 0) AS DDJ_RENUNCIADESIGNACION--VALOR EN SIGA = 2
      , DECODE(EJG.IDRENUNCIA, 1, 3, NULL) AS DDJ_RENUNCIAHONORARIOS--VALOR EN SIGA = 1
      --, DECODE(EJG.CALIDAD, 'D', 1, 0) AS DDJ_DEMANDADODEMANDANTE
      , (SELECT T.CODIGO FROM SCS_TIPOENCALIDAD T WHERE T.IDINSTITUCION = EJG.IDINSTITUCION AND T.IDTIPOENCALIDAD = EJG.IDTIPOENCALIDAD) AS DDJ_DEMANDADODEMANDANTE
      , (SELECT DECODE(P.CODIGOEXT, NULL, NULL, P.CODIGOEXT || '##' || F_SIGA_GETRECURSO(P.DESCRIPCION, LEN.IDLENGUAJE))
                FROM SCS_PRECEPTIVO P
                WHERE P.IDPRECEPTIVO = EJG.IDPRECEPTIVO) AS DDJ_PRECEPTIVO_CDA
      , EJG.NIG AS DDJ_NIG
      , (SELECT T.CODIGOEJIS FROM SCS_TIPOENCALIDAD T WHERE T.IDINSTITUCION = EJG.IDINSTITUCION AND T.IDTIPOENCALIDAD = EJG.IDTIPOENCALIDAD) AS DDJ_SITUACION_PROCESAL_CDA
      , (SELECT SIT.CODIGOEJIS || '##' || f_siga_getrecurso(SIT.DESCRIPCION, LEN.IDLENGUAJE)
                               FROM SCS_SITUACION SIT WHERE SIT.IDSITUACION = EJG.IDSITUACION) AS DDJ_SITUACION_PROCEDIM_CDA
      --Datos Asistencia Detenido PRETENSION
      , (CASE WHEN (NVL(PRE_D.CODIGOEXT, PRE.CODIGOEXT) IN ('4100500000','4100501000','4100502000','4100503000'))  --Recurs administratiu (estrangeria), Recurs Alçada, Recurs Reposició, Devolució/Expulsió
              THEN 3 --PROCEDIMIENTO ADMINISTRATIVO
              --ñapa para que entren como asistencia penal. Ver correos del 12/02/2014
--              WHEN (NVL(PRE_D.CODIGOEXT, PRE.CODIGOEXT) IN ('2101501000','2101502000', '0') OR (EJGREMESA.IDINSTITUCION || EJGREMESA.IDREMESA) = 2047159)--Atestat, Diligència, Altres
              WHEN NVL(PRE_D.CODIGOEXT, PRE.CODIGOEXT) IN ('2101501000','2101502000', '0')--Atestat, Diligència, Altres
              THEN 2 --ASISTENCIA PENAL
              ELSE 1 --PROCEDIMIENTO_JUDICIAL
              END) AS PRETENSION_CHOICE
      , VASIS.CAT_PARTIDO_JUDICIAL_ASIS
      , DECODE(VASIS.NUMERODILIGENCIA, NULL, VASIS.NUMEROATESTADO, NULL) AS DAD_NUMEROATESTADO --LP: es el número de diligencia
      , DECODE(VASIS.NUMERODILIGENCIA, NULL, VASIS.FECHAASISTENCIAATESTADO, NULL) AS DAD_FECHAASISTENCIAATESTADO
      , DECODE(VASIS.NUMERODILIGENCIA, NULL, VASIS.CENTRODETENCION_CDA, NULL) AS DAD_CENTRODETENCION_CDA
      , DECODE (VASIS.NUMEROATESTADO, NULL, VASIS.NUMERODILIGENCIA, NULL) AS DAD_NUMERODILIGENCIA --LP: es el número de procedimiento
      , DECODE (VASIS.NUMEROATESTADO, NULL, VASIS.FECHAASISTENCIADILIGENCIA, NULL) AS DAD_FECHAASISTENCIADILIGENCIA
      , DECODE (VASIS.NUMEROATESTADO, NULL, VASIS.ORGANOJUDICIAL_CDA, NULL) AS DAD_ORGANOJUDICIAL_CDA
      , (SELECT C.NCOLEGIADO FROM CEN_COLEGIADO C
                WHERE C.IDINSTITUCION = VASIS.IDINSTITUCION
                AND C.IDPERSONA = VASIS.IDPERSONACOLEGIADO) AS DAD_AA_NUMCOLEGIADOABOGADO
      , (CASE WHEN VASIS.FECHAASISTENCIADILIGENCIA IS NOT NULL
              THEN 1
              WHEN VASIS.FECHAASISTENCIAATESTADO IS NOT NULL
              THEN 0
              ELSE NULL
              END) AS DAD_ESATESTADO
      , VASIS.TIPODELITO_CDA AS DAD_TIPODELITO_CDA
      --Datos Tramitacion Expediente
        --Tramite Archivo (Intercambio IEA)
        , DECODE(LEN.IDLENGUAJE, 2, '2##Arxivat', '2##Archivado') AS DTE_TA_IT_ESTADOEXPEDIENTE_CDA
        , (SELECT EE.FECHAINICIO
                   FROM SCS_ESTADOEJG EE
                   WHERE EE.IDINSTITUCION = EJG.IDINSTITUCION
                   AND EE.ANIO = EJG.ANIO
                   AND EE.IDTIPOEJG = EJG.IDTIPOEJG
                   AND EE.NUMERO = EJG.NUMERO
                   AND EE.IDESTADOEJG = 12 --ARCHIVADO
                   AND EE.IDESTADOPOREJG = (SELECT MAX(EE2.IDESTADOPOREJG)
                                      FROM SCS_ESTADOEJG EE2
                                      WHERE  EE2.IDINSTITUCION = EE.IDINSTITUCION
                                      AND EE2.ANIO = EE.ANIO
                                      AND EE2.IDTIPOEJG = EE.IDTIPOEJG
                                      AND EE2.NUMERO = EE.NUMERO
                                      and EE2.fechabaja is null
                                      AND EE2.IDESTADOEJG = 12) --ARCHIVADO
                                      ) AS DTE_TA_IT_FECHAESTADO
        --Trámite Dictamen (Intercambio IED)
        , (CASE WHEN EJG.FECHADICTAMEN IS NULL
                THEN NULL
                WHEN I.CEN_INST_IDINSTITUCION IN (3003, 3004,3009)
                THEN '30##Dictaminado por el ICA'
                ELSE DECODE(LEN.IDLENGUAJE, 2, '3##Dictaminat', '3##Dictaminado')
                END) AS DTE_TD_IT_ESTADOEXPEDIENTE_CDA
        , EJG.FECHADICTAMEN AS DTE_TD_IT_FECHAESTADO
        , (SELECT TD.CODIGOEXT || '##' || F_SIGA_GETRECURSO(TD.DESCRIPCION, LEN.IDLENGUAJE)
                      FROM SCS_TIPODICTAMENEJG TD
                      WHERE TD.IDINSTITUCION = EJG.IDINSTITUCION
                      AND TD.IDTIPODICTAMENEJG = EJG.IDTIPODICTAMENEJG) AS DTE_TD_TIPODICTAMEN_CDA
        , (SELECT TF.CODIGO || '##' || F_SIGA_GETRECURSO(TF.DESCRIPCION, LEN.IDLENGUAJE)
                      FROM SCS_TIPOFUNDAMENTOCALIF TF
                      WHERE TF.IDINSTITUCION = EJG.IDINSTITUCION
                      AND TF.IDFUNDAMENTOCALIF = EJG.IDFUNDAMENTOCALIF) AS DTE_TD_MOTIVODICTAMEN_CDA
        , NULL AS DTE_TD_INTERVALOINGRESOSRECURS --NO HAY INFORMACION EN SIGA
        , EJG.DICTAMEN AS DTE_TD_OBSERVACIONESDICTAMEN
        --Tramite Resolucion (Intercambio IR)
        , NULL AS DTE_TR_IT_ESTADOEXPEDIENTE_CDA
        , NULL AS DTE_TR_IT_FECHAESTADO
        , NULL AS DTE_TR_IDENTIFICADORRESOLUCION
        , NULL AS DTE_TR_TIPORESOLUCION_CDA
        , NULL AS DTE_TR_MOTIVORESOLUCION_CDA
        , NULL AS DTE_TR_INTERVALOINGRESOSRECURS
        , NULL AS DTE_TR_PR_TIPOPRESTACION_CDA
 FROM SCS_EJG EJG
      , CAJG_EJGREMESA EJGREMESA
      , SCS_PROCURADOR PROC
      , V_PCAJG_M_DPERSONA VDP
      , V_PCAJG_M_DPERSONA VDP_REP
      , SCS_PRETENSION PRE
      , SCS_JURISDICCION JUR
      , SCS_PRETENSION PRE_D
      , SCS_JURISDICCION JUR_D
      , SCS_UNIDADFAMILIAREJG UF
      , V_PCAJG_EJGPROCURADOR VPROC
      , V_PCAJG_ASISTACTUACEJG VASIS
      , SCS_EJGDESIGNA ED
      , SCS_DESIGNA D
      , ADM_LENGUAJES LEN
      , CEN_INSTITUCION I
 WHERE EJG.IDINSTITUCION =  EJGREMESA.IDINSTITUCION
   AND EJG.ANIO = EJGREMESA.ANIO
   and EJG.NUMERO = EJGREMESA.NUMERO
   and EJG.IDTIPOEJG = EJGREMESA.IDTIPOEJG
   AND EJG.IDINSTITUCION_PROC = PROC.IDINSTITUCION(+)
   AND EJG.IDPROCURADOR = PROC.IDPROCURADOR(+)
   AND EJG.IDINSTITUCION = VDP.IDINSTITUCION
   AND EJG.IDPERSONAJG = VDP.IDPERSONA
   AND LEN.IDLENGUAJE = VDP.IDLENGUAJE
   AND VDP.IDINSTITUCION = VDP_REP.IDINSTITUCION(+)
   AND VDP.IDREPRESENTANTEJG = VDP_REP.IDPERSONA(+)
   AND (VDP_REP.IDLENGUAJE IS NULL OR LEN.IDLENGUAJE = VDP_REP.IDLENGUAJE)
   AND EJG.IDINSTITUCION = PRE.IDINSTITUCION(+)
   AND EJG.IDPRETENSION = PRE.IDPRETENSION(+)
   AND PRE.IDJURISDICCION = JUR.IDJURISDICCION(+)
   AND D.IDINSTITUCION = PRE_D.IDINSTITUCION(+)
   AND D.IDPRETENSION = PRE_D.IDPRETENSION(+)
   AND PRE_D.IDJURISDICCION = JUR_d.IDJURISDICCION(+)
   AND EJG.IDINSTITUCION = UF.IDINSTITUCION(+)
   AND EJG.IDTIPOEJG = UF.IDTIPOEJG(+)
   AND EJG.ANIO = UF.ANIO(+)
   AND EJG.NUMERO = UF.NUMERO(+)
   AND EJG.IDPERSONAJG = UF.IDPERSONA(+)
   AND EJG.IDINSTITUCION = VPROC.IDINSTITUCION(+)
   AND EJG.ANIO = VPROC.ANIOEJG(+)
   AND EJG.NUMERO = VPROC.NUMEROEJG(+)
   AND EJG.IDTIPOEJG = VPROC.IDTIPOEJG(+)
   AND EJG.IDINSTITUCION = VASIS.IDINSTITUCION(+)
   AND EJG.NUMERO = VASIS.NUMERO(+)
   AND EJG.IDTIPOEJG = VASIS.IDTIPOEJG(+)
   AND EJG.ANIO = VASIS.ANIO(+)
   AND EJG.IDINSTITUCION = ED.IDINSTITUCION(+)
   AND EJG.IDTIPOEJG = ED.IDTIPOEJG(+)
   AND EJG.ANIO = ED.ANIOEJG(+)
   AND EJG.NUMERO = ED.NUMEROEJG(+)
   --si hay mas de una designa cogemos la primera (LP)
   AND (ED.NUMEROEJG IS NULL OR ED.ANIODESIGNA || LPAD(ED.NUMERODESIGNA, 10, '0') =
          (SELECT MAX(ED2.ANIODESIGNA || LPAD(ED2.NUMERODESIGNA, 10, '0'))
          FROM SCS_EJGDESIGNA ED2
          WHERE ED2.IDINSTITUCION = EJG.IDINSTITUCION
          AND ED2.ANIOEJG = EJG.ANIO
          AND ED2.NUMEROEJG = EJG.NUMERO
          AND ED2.IDTIPOEJG = EJG.IDTIPOEJG))
   AND ED.IDINSTITUCION = D.IDINSTITUCION(+)
   AND ED.IDTURNO = D.IDTURNO(+)
   AND ED.ANIODESIGNA = D.ANIO(+)
   AND ED.NUMERODESIGNA = D.NUMERO(+)
   AND EJGREMESA.IDINSTITUCION = I.IDINSTITUCION;
/