CREATE OR REPLACE VIEW V_PCAJG_DOCUMENTACIONEXP_CAT AS
SELECT IDINSTITUCION
      , IDTIPOEJG
      , ANIO
      , NUMERO
      , IDREMESA
      , IDPERSONA
      , IDLENGUAJE
      , TIPODOCUMENTACION_CDA AS DS_DE_D_TIPODOCUMENTACION_CDA
      , TIPODOCUMENTO_CDA AS DS_DE_D_DD_TIPODOCUMENTO_CDA
      , CODIGOEXT AS DS_DE_D_DD_CODIGOEXT
      , FECHAPRESENTACIONDO AS DS_DE_D_DD_FECHAPRESENTACIONDO
      , DESCRIPCIONAMPLIADA AS DS_DE_D_DD_DESCRIPCIONAMPLIADA
      , PROCEDENTE AS DS_DE_D_DD_PROCEDENTE
      , NOMBRE_ARCHIVO AS DS_DE_D_DD_NOMBRE_ARCHIVO
      , EXTENSION_ARCHIVO AS DS_DE_D_DD_EXTENSION_ARCHIVO
      , DIRECTORIO_ARCHIVO AS DS_DE_D_DD_DIRECTORIO_ARCHIVO
FROM V_PCAJG_M_DOCUMENTACIONEXP
WHERE codigoext IN ('TR-DOCINISOL-01','TR-DOCINIJUS-01','TR-DOCINIACA-01','TR-DOCINIDIC-01',
                   'TR-DOCINIDES-01','TR-ALBASS-01','TR-ALTIN-01','TR-CERAJUTS-01','TR-CERBEN-01',
                   'TR-CERCETRE-01','TR-CEREMP-01','TR-CERINEM-01','TR-CERPEN-01','TR-CERTISS-01',
                   'TR-CERVAL-01','TR-CONLLO-01','TR-DECPUB-01','TR-DEINPER-01','TR-DERPF-01',
                   'TR-DESPES-01','TR-DOCACRE-01','TR-IMPAT-01','TR-IMPSOC-01','TR-INFVILAB-01',
                   'TR-INSREG-01','TR-LLIFA-01','TR-MINUSV-01','TR-SEPARA-01','TR-SOLAJGF-01',
                   'TR-SOLAJGJ-01','TR-TITIMM-01');
 
