CREATE OR REPLACE VIEW USCGAE.V_PCAJG_M_DOCUMENTACIONEXP AS
SELECT ER.IDINSTITUCION
      , ER.IDTIPOEJG
      , ER.ANIO
      , ER.NUMERO
      , ER.IDREMESA
      , LEN.IDLENGUAJE
      , DOCN.PRESENTADOR AS IDPERSONA
      , TD.IDTIPODOCUMENTOEJG || '##'
              || F_SIGA_GETRECURSO(TD.DESCRIPCION, LEN.IDLENGUAJE) AS TIPODOCUMENTACION_CDA 
      , DOC.IDDOCUMENTOEJG || '##'
              || F_SIGA_GETRECURSO(DOC.ABREVIATURA, LEN.IDLENGUAJE) AS TIPODOCUMENTO_CDA 
      , DOC.CODIGOEXT AS CODIGOEXT
      , DOCN.FECHAENTREGA AS FECHAPRESENTACIONDO
      , F_SIGA_GETRECURSO(DOC.DESCRIPCION, LEN.IDLENGUAJE) AS DESCRIPCIONAMPLIADA
      , NULL AS PROCEDENTE --TODO
      , FIC.IDINSTITUCION || '_' || FIC.IDFICHERO AS NOMBRE_ARCHIVO
      , FIC.EXTENSION AS EXTENSION_ARCHIVO
      , FIC.DIRECTORIO AS DIRECTORIO_ARCHIVO
FROM CAJG_EJGREMESA ER, SCS_DOCUMENTACIONEJG DOCN, SCS_DOCUMENTOEJG DOC, SCS_TIPODOCUMENTOEJG TD, ADM_LENGUAJES LEN, GEN_FICHERO FIC, CEN_INSTITUCION I
WHERE ER.IDINSTITUCION = DOCN.IDINSTITUCION
  AND ER.ANIO = DOCN.ANIO
  AND ER.NUMERO = DOCN.NUMERO
  AND ER.IDTIPOEJG = DOCN.IDTIPOEJG
  AND DOCN.IDINSTITUCION = DOC.IDINSTITUCION
  AND DOCN.IDTIPODOCUMENTO = DOC.IDTIPODOCUMENTOEJG
  AND DOCN.IDDOCUMENTO = DOC.IDDOCUMENTOEJG
  AND DOC.IDINSTITUCION = TD.IDINSTITUCION
  AND DOC.IDTIPODOCUMENTOEJG = TD.IDTIPODOCUMENTOEJG
  AND LEN.IDLENGUAJE = 2
  AND DOCN.IDFICHERO = FIC.IDFICHERO
  AND DOCN.IDINSTITUCION = FIC.IDINSTITUCION
  AND ER.IDINSTITUCION = I.IDINSTITUCION
  AND I.Cen_Inst_Idinstitucion = 3001
