CREATE OR REPLACE FORCE VIEW V_SIGA_SOLICITANTES_EJG ("IDINSTITUCION", "IDTIPOEJG", "ANIO", "NUMERO", "IDPERSONAJG", "IDTIPOGRUPOLAB", "CALIDAD", "IDTIPOENCALIDAD", "CALIDADIDINSTITUCION", "NOMBRE", "APELLIDO1", "APELLIDO2", "DIRECCION", "CODIGOPOSTAL", "NOMBRE_POB", "NOMBRE_PROV", "NOMBRE_PAIS", "ANIOEJG", "NUMEJG", "NIF", "SEXO", "IDLENGUAJE", "TELEFONO", "TELEFONOLIST", "OBSERVACIONES") AS 
  SELECT UFA.IDINSTITUCION, UFA.IDTIPOEJG, UFA.ANIO, UFA.NUMERO, UFA.IDPERSONA IDPERSONAJG, UFA.IDTIPOGRUPOLAB, EJG3.CALIDAD AS CALIDAD,EJG3.IDTIPOENCALIDAD AS IDTIPOENCALIDAD,EJG3.CALIDADIDINSTITUCION AS CALIDADIDINSTITUCION,
         PER2.NOMBRE, PER2.APELLIDO1, PER2.APELLIDO2, PER2.DIRECCION, PER2.CODIGOPOSTAL, POB.NOMBRE AS NOMBRE_POB, PROV.NOMBRE AS NOMBRE_PROV, PAIS.NOMBRE AS NOMBRE_PAIS, EJG3.ANIO AS ANIOEJG, EJG3.NUMEJG, PER2.NIF, PER2.SEXO, PER2.IDLENGUAJE,
         (SELECT TEL2.NUMEROTELEFONO FROM SCS_TELEFONOSPERSONA TEL2 WHERE TEL2.IDINSTITUCION=UFA.IDINSTITUCION AND TEL2.IDPERSONA=UFA.IDPERSONA AND ROWNUM<2) AS TELEFONO,
         (SELECT LISTAGG(LTEL.NOMBRETELEFONO||':'||LTEL.NUMEROTELEFONO, ',') within group (order by rownum) from SCS_TELEFONOSPERSONA LTEL WHERE LTEL.IDINSTITUCION = UFA.IDINSTITUCION AND LTEL.IDPERSONA = UFA.IDPERSONA) AS TELEFONOLIST,
         PER2.OBSERVACIONES
   FROM SCS_UNIDADFAMILIAREJG UFA, SCS_PERSONAJG PER2, CEN_POBLACIONES POB, CEN_PROVINCIAS PROV, CEN_PAIS PAIS, SCS_EJG EJG3
   WHERE UFA.IDINSTITUCION=PER2.IDINSTITUCION
     AND UFA.SOLICITANTE=1
     AND UFA.IDPERSONA=PER2.IDPERSONA
     AND UFA.IDINSTITUCION=EJG3.IDINSTITUCION
     AND UFA.IDTIPOEJG=EJG3.IDTIPOEJG
     AND UFA.ANIO=EJG3.ANIO
     AND UFA.NUMERO=EJG3.NUMERO
     AND PER2.IDPOBLACION = POB.IDPOBLACION (+)
     AND PER2.IDPROVINCIA = PROV.IDPROVINCIA (+)
     AND PER2.IDPAIS = PAIS.IDPAIS (+)
ORDER BY IDINSTITUCION, IDTIPOEJG, ANIO, NUMERO, IDPERSONAJG
/
