CREATE OR REPLACE FORCE VIEW V_SIGA_DEFENDIDOS_DESIGNA ("IDINSTITUCION", "IDTURNO", "ANIO", "NUMERO", "IDPERSONAJG", "CALIDAD", "IDTIPOENCALIDAD", "CALIDADIDINSTITUCION", "NOMBRE", "APELLIDO1", "APELLIDO2", "DIRECCION", "CODIGOPOSTAL", "NOMBRE_POB", "NOMBRE_PROV", "NOMBRE_PAIS", "NIF", "SEXO", "IDLENGUAJE", "TELEFONO", "TELEFONOLIST", "OBSERVACIONES") AS 
  SELECT DEF.IDINSTITUCION,
       DEF.IDTURNO,
       DEF.ANIO,
       DEF.NUMERO,
       DEF.IDPERSONA IDPERSONAJG,
       DEF.CALIDAD,
       DEF.IDTIPOENCALIDAD,
       DEF.CALIDADIDINSTITUCION,
       PER.NOMBRE,
       PER.APELLIDO1,
       PER.APELLIDO2,
       PER.DIRECCION,
       PER.CODIGOPOSTAL,
       POB.NOMBRE AS NOMBRE_POB,
       PROV.NOMBRE AS NOMBRE_PROV,
       PAIS.NOMBRE AS NOMBRE_PAIS,
       PER.NIF,
       PER.SEXO,
       PER.IDLENGUAJE,
       (SELECT TEL2.NUMEROTELEFONO
          FROM SCS_TELEFONOSPERSONA TEL2
         WHERE TEL2.IDINSTITUCION = PER.IDINSTITUCION
           AND TEL2.IDPERSONA = PER.IDPERSONA
           AND ROWNUM < 2) AS TELEFONO,
       (SELECT LISTAGG(LTEL.NOMBRETELEFONO||':'||LTEL.NUMEROTELEFONO, ',') within group (order by rownum) from SCS_TELEFONOSPERSONA LTEL WHERE LTEL.IDINSTITUCION = PER.IDINSTITUCION AND LTEL.IDPERSONA = PER.IDPERSONA) AS TELEFONOLIST,
       PER.OBSERVACIONES
  FROM SCS_DEFENDIDOSDESIGNA DEF,
       SCS_PERSONAJG         PER,
       CEN_POBLACIONES       POB,
       CEN_PROVINCIAS        PROV,
       CEN_PAIS              PAIS
 WHERE DEF.IDINSTITUCION = PER.IDINSTITUCION
   AND DEF.IDPERSONA = PER.IDPERSONA
   AND PER.IDPOBLACION = POB.IDPOBLACION(+)
   AND PER.IDPROVINCIA = PROV.IDPROVINCIA(+)
   AND PER.IDPAIS = PAIS.IDPAIS(+)
 ORDER BY DEF.IDINSTITUCION,
          DEF.IDTURNO,
          DEF.ANIO,
          DEF.NUMERO,
          DEF.IDPERSONA
/
