CREATE OR REPLACE VIEW USCGAE.V_WS_2064_PERSONA AS
SELECT P.IDPERSONA,
       EJGREMESA.IDREMESA,
       EJGREMESA.IDEJGREMESA,
       EJGREMESA.IDINSTITUCION,
       EJG.ANIO,
       EJG.NUMERO,
       EJG.IDTIPOEJG,
       DECODE(P.IDPERSONA, EJG.IDPERSONAJG, 1, 0) AS IS_SOLICITANTE,
       DECODE(PAR.CODIGOEXT, 21, 1, 0) AS IS_CONYUGE,
       TRIM(P.NOMBRE) AS NOME --OB
      ,
       TRIM(P.APELLIDO1) AS APELLIDO1,
       TRIM(P.APELLIDO2) AS APELLIDO2
       --, PAIS.CODIGOEXT AS NACIONALIDADE
      ,
       NULL AS NACIONALIDADE,
       (CASE P.IDESTADOCIVIL
         WHEN 1 --Casado
          THEN
          2
         WHEN 2 --SOLTERO
          THEN
          1
         WHEN 3 --VIUDO
          THEN
          4
         WHEN 4 --SEPARADO
          THEN
          5
         WHEN 5 --DIVORCIADO
          THEN
          3
         WHEN 6 --PAREJA DE HECHO
          THEN
          NULL
         WHEN 7 --DESCONOCIDO
          THEN
          NULL
         ELSE
          NULL
       END) AS ESTADO_CIVIL,
       (SELECT PI.CODIGO
          FROM PCAJG_TIPO_IDENTIFICACION      PI,
               PCAJG_TIPO_IDENTIFICACION_CENT PS
         WHERE PI.IDENTIFICADOR = PS.IDENTIFICADOR
           AND PI.IDINSTITUCION = PS.IDINSTITUCION
           AND PS.IDTIPOIDENTIFICACION = P.IDTIPOIDENTIFICACION
           AND PS.IDINSTITUCION = P.IDINSTITUCION) AS TIPOIDENTIFICADOR,
       UPPER(P.NIF) AS NIF,
       P.FECHANACIMIENTO AS DATA_NACEMENTO,
       TRUNC(MONTHS_BETWEEN(SYSDATE, P.FECHANACIMIENTO) / 12) AS IDADE,
       P.DIRECCION AS DC_ENDEREZO,
       DECODE(POB.IDPOBLACION, 0, '', SUBSTR(POB.NOMBRE, 1, 25)) AS DC_LOCALIDADE,
       DECODE(POB.IDPOBLACION, 0, '99999', SUBSTR(POB.CODIGOEXT, 1, 5)) AS DC_MUNICIPIO,
       DECODE(PROV.IDPROVINCIA, 00, '99', PROV.CODIGOEXT) AS DC_PROVINCIA,
       P.CODIGOPOSTAL AS DC_CODPOSTAL,
       F_SIGA_GETTELEFONOPERSONAJG(P.IDINSTITUCION, P.IDPERSONA, 1) AS DC_TELEFONO,
       NULL AS DC_FAX,
       NULL AS DC_CORREO_ELECTRONICO,
       NULL AS PROFESION,
       NULL AS EMPRESA,
       NULL AS REGIMEN_COTIZACION
       --      , NULL AS ES_PERSONA_FISICA
       --      , NULL AS SEXO
      ,
       DECODE(P.TIPOPERSONAJG, 'F', 1, 0) AS ES_PERSONA_FISICA,
       DECODE(P.SEXO, 'H', 'M', 'M', 'F', NULL) AS SEXO,
       PAR.CODIGOEXT AS PARENTESCO
       --DATOS ECONOMICOS
      ,
       NULL AS DE_INGRESO_IMP,
       NULL AS DE_INGRESO_CONCEPTO,
       NULL AS DE_BI_TIPO,
       NULL AS DE_BI_VALORACION,
       NULL AS DE_BI_TIPOVALORACION,
       NULL AS DE_BI_CARGAS,
       NULL AS DE_BM_TIPO,
       NULL AS DE_BE_VALORACION,
       NULL AS DE_BE_MATRICULA,
       NULL AS DE_ALQUILER_RMENSUAL,
       NULL AS DE_OUTROS_DATOS
       --AUTORIZACIONES
      ,
       DECODE((SELECT COUNT(1)
                FROM SCS_EEJG_PETICIONES EEJG
               WHERE UF.IDINSTITUCION = EEJG.IDINSTITUCION
                 AND UF.IDTIPOEJG = EEJG.IDTIPOEJG
                 AND UF.ANIO = EEJG.ANIO
                 AND UF.NUMERO = EEJG.NUMERO
                 AND UF.IDPERSONA = EEJG.IDPERSONA),
              0,
              'N',
              'S') AS A_AEAT_TGSS_CATASTRO,
       'N' AS A_DISCAPACIDAD,
       'N' AS A_ESTADO_DESEMPLEO,
       'N' AS A_PRESTACION_DESEMPLEO,
       'N' AS A_PRESTACIONES_MATERNIDAD,
       'N' AS A_PAREJA_DE_HECHO,
       'N' AS A_FAMILIA_NUMEROSA,
       'S' AS A_IDENTIDAD --TODO CAMPO OBLIGATORIO QUE HAY QUE METER NUEVO CHECK EN SIGA. PENDIENTE DE APROBAR LP.
  FROM SCS_PERSONAJG         P,
       CEN_PAIS              PAIS,
       CEN_POBLACIONES       POB,
       CEN_PROVINCIAS        PROV,
       SCS_UNIDADFAMILIAREJG UF,
       SCS_EJG               EJG,
       SCS_PARENTESCO        PAR,
       CAJG_EJGREMESA        EJGREMESA

 WHERE P.IDPAIS = PAIS.IDPAIS(+)
   AND P.IDPOBLACION = POB.IDPOBLACION(+)
   AND P.IDPROVINCIA = PROV.IDPROVINCIA(+)
   AND UF.IDINSTITUCION = P.IDINSTITUCION
   AND UF.IDPERSONA = P.IDPERSONA
   AND UF.IDINSTITUCION = EJG.IDINSTITUCION
   AND UF.ANIO = EJG.ANIO
   AND UF.NUMERO = EJG.NUMERO
   AND UF.IDTIPOEJG = EJG.IDTIPOEJG
   AND UF.IDINSTITUCION = PAR.IDINSTITUCION(+)
   AND UF.IDPARENTESCO = PAR.IDPARENTESCO(+)
   AND EJG.IDINSTITUCION = EJGREMESA.IDINSTITUCION
   AND EJG.ANIO = EJGREMESA.ANIO
   AND EJG.NUMERO = EJGREMESA.NUMERO
   AND EJG.IDTIPOEJG = EJGREMESA.IDTIPOEJG

