CREATE OR REPLACE VIEW USCGAE.V_WS_2032_PROFDESIG AS
SELECT EJGREMESA.IDREMESA
      , EJGREMESA.IDINSTITUCION
      , EJG.IDTIPOEJG
      , EJG.ANIO
      , EJG.NUMERO
      , EJG.NUMEJG
      , EJGREMESA.IDEJGREMESA
      , I.CODIGOEXT AS PD_COLEGIO
      , (CASE
              WHEN EJG.IDPRECEPTIVO IN (1,3) AND (SELECT DC.CODIGOEXT
                                      FROM SCS_TIPODESIGNACOLEGIO DC
                                      WHERE DC.IDINSTITUCION = D.IDINSTITUCION
                                      AND DC.IDTIPODESIGNACOLEGIO = D.IDTIPODESIGNACOLEGIO) = '1'
              THEN 1
              ELSE 0
              END) AS PD_DEOFICIO
      , 'DES' AS PD_ESTADODESIGNACION--TODO
      , TO_CHAR(DL.FECHADESIGNA, 'DD/MM/YYYY') AS PD_FECHADESIGNACION
      , NULL AS PD_FECHAESTADODESIGNACION
      , NULL AS PD_FECHARENUNCIAHONORARIOS
      , LPAD(COL.NCOLEGIADO, 6, '0') AS PD_NUMEROCOLEGIADO
      , PER.NIFCIF AS PD_NUMEROIDENTIFICACION
      , PER.NOMBRE||' '||NVL(PER.APELLIDOS1,'')||' '||NVL(PER.APELLIDOS2,'') AS PD_NOMBREPROFESIONAL
      , DECODE(EJG.IDRENUNCIA, 1, '1', '0') AS PD_RENUNCIAHONORARIOS
      , (CASE PER.IDTIPOIDENTIFICACION
              WHEN 10--NIF
              THEN 'N'
              WHEN 20--CIF
              THEN 'C'
              WHEN 30--Pasaporte
              THEN 'T'
              WHEN 40--NIE
              THEN 'X'
              WHEN 50--Otro
              THEN 'I'--
              WHEN NULL
              THEN 'I'
              ELSE NULL
              END) AS PD_TIPOIDENTIFICADOR--CEN_TIPOIDENTIFICACION
      , 'ABO' AS PD_TIPOPROFESIONAL
FROM SCS_EJG EJG
     , CAJG_EJGREMESA EJGREMESA
     , SCS_EJGDESIGNA ED
     , SCS_DESIGNA D
     , SCS_DESIGNASLETRADO DL
     , CEN_COLEGIADO COL
     , CEN_PERSONA PER
     , CEN_INSTITUCION I
 WHERE EJG.IDINSTITUCION =  EJGREMESA.IDINSTITUCION
   AND EJG.ANIO = EJGREMESA.ANIO
   AND EJG.NUMERO = EJGREMESA.NUMERO
   AND EJG.IDTIPOEJG = EJGREMESA.IDTIPOEJG
   AND EJG.IDINSTITUCION = ED.IDINSTITUCION(+)
   AND EJG.IDTIPOEJG = ED.IDTIPOEJG(+)
   AND EJG.ANIO = ED.ANIOEJG(+)
   AND EJG.NUMERO = ED.NUMEROEJG(+)
   --si hay mas de una designa cogemos la primera (LP)
   AND (ED.NUMEROEJG IS NULL OR ED.ANIODESIGNA || LPAD(ED.NUMERODESIGNA, 10, '0') =
          (SELECT MIN(ED2.ANIODESIGNA || LPAD(ED2.NUMERODESIGNA, 10, '0'))
          FROM SCS_EJGDESIGNA ED2
          WHERE ED2.IDINSTITUCION = EJG.IDINSTITUCION
          AND ED2.ANIOEJG = EJG.ANIO
          AND ED2.NUMEROEJG = EJG.NUMERO
          AND ED2.IDTIPOEJG = EJG.IDTIPOEJG))
   AND ED.IDINSTITUCION = D.IDINSTITUCION(+)
   AND ED.IDTURNO = D.IDTURNO(+)
   AND ED.ANIODESIGNA = D.ANIO(+)
   AND ED.NUMERODESIGNA = D.NUMERO(+)
   AND D.IDINSTITUCION = DL.IDINSTITUCION
   AND D.IDTURNO = DL.IDTURNO
   AND D.ANIO = DL.ANIO
   AND D.NUMERO = DL.NUMERO
   AND DL.IDINSTITUCION = COL.IDINSTITUCION
   AND DL.IDPERSONA = COL.IDPERSONA
   AND COL.IDPERSONA = PER.IDPERSONA
   AND EJG.IDINSTITUCION = I.IDINSTITUCION
UNION
SELECT EJGREMESA.IDREMESA
      , EJGREMESA.IDINSTITUCION
      , EJG.IDTIPOEJG
      , EJG.ANIO
      , EJG.NUMERO
      , EJG.NUMEJG
      , EJGREMESA.IDEJGREMESA
      , 'P20069' AS PD_COLEGIO
      , (CASE
              WHEN EJG.IDPRECEPTIVO = 1 AND (SELECT DC.CODIGOEXT
                                      FROM SCS_TIPODESIGNACOLEGIO DC
                                      WHERE DC.IDINSTITUCION = D.IDINSTITUCION
                                      AND DC.IDTIPODESIGNACOLEGIO = D.IDTIPODESIGNACOLEGIO) = '1'
              THEN 1
              ELSE 0
              END) AS PD_DEOFICIO
      , 'DES' AS PD_ESTADODESIGNACION--TODO
      , TO_CHAR(DP.FECHADESIGNA, 'DD/MM/YYYY') AS PD_FECHADESIGNACION
      , NULL AS PD_FECHAESTADODESIGNACION
      , NULL AS PD_FECHARENUNCIAHONORARIOS
      , PROCDES.NCOLEGIADO AS PD_NUMEROCOLEGIADO
      , '12345678Z' AS PD_NUMEROIDENTIFICACION
      , PROCDES.NOMBRE||' '||NVL(PROCDES.APELLIDOS1,'')||' '||NVL(PROCDES.APELLIDOS2,'') AS PD_NOMBREPROFESIONAL
      , '0' AS PD_RENUNCIAHONORARIOS
      , 'N' AS PD_TIPOIDENTIFICADOR
      , 'PRO' AS PD_TIPOPROFESIONAL
 FROM SCS_EJG EJG,
   CAJG_EJGREMESA EJGREMESA,
   SCS_EJGDESIGNA ED,
   SCS_DESIGNA D,
   SCS_DESIGNAPROCURADOR DP,
   SCS_PROCURADOR PROCDES,
   CEN_INSTITUCION I
 WHERE EJG.IDINSTITUCION =  EJGREMESA.IDINSTITUCION
   AND EJG.ANIO = EJGREMESA.ANIO
   AND EJG.NUMERO = EJGREMESA.NUMERO
   AND EJG.IDTIPOEJG = EJGREMESA.IDTIPOEJG
   AND EJG.IDINSTITUCION = ED.IDINSTITUCION
   AND EJG.ANIO = ED.ANIOEJG
   AND EJG.NUMERO = ED.NUMEROEJG
   AND EJG.IDTIPOEJG = ED.IDTIPOEJG
   AND ED.IDINSTITUCION = D.IDINSTITUCION
   AND ED.IDTURNO = D.IDTURNO
   AND ED.ANIODESIGNA = D.ANIO
   AND ED.NUMERODESIGNA = D.NUMERO
   AND D.IDINSTITUCION = DP.IDINSTITUCION
   AND D.IDTURNO = DP.IDTURNO
   AND D.ANIO = DP.ANIO
   AND D.NUMERO = DP.NUMERO
   AND DP.IDINSTITUCION_PROC = PROCDES.IDINSTITUCION
   AND DP.IDPROCURADOR = PROCDES.IDPROCURADOR
   AND DP.FECHARENUNCIA IS NULL
   AND (ED.ANIODESIGNA || LPAD(ED.NUMERODESIGNA, 10, 0)) =
       (SELECT MIN(ED2.ANIODESIGNA || LPAD(ED2.NUMERODESIGNA, 10, 0))
          FROM SCS_EJGDESIGNA ED2
         WHERE ED2.IDINSTITUCION = EJG.IDINSTITUCION
           AND ED2.ANIOEJG = EJG.ANIO
           AND ED2.NUMEROEJG = EJG.NUMERO
           AND ED2.IDTIPOEJG = EJG.IDTIPOEJG)
   AND EJG.IDINSTITUCION = I.IDINSTITUCION
