CREATE OR REPLACE VIEW V_WS_JE_2064_DESIGNAPROCURADOR AS
SELECT ADP.IDINSTITUCION
        , ADP.IDFACTURACIONPROCURADOR AS IDFACTURACION
        , F_SIGA_GET_IDULTIMOESTADOEJG(EJG.IDINSTITUCION, EJG.IDTIPOEJG, EJG.ANIO, EJG.NUMERO) AS ULTIMO_ESTADO_EJG
        --
       , SUBSTR(ADP.IDFACTURACIONPROCURADOR, 1, 4) AS PERIODO_ANO
       , SUBSTR(ADP.IDFACTURACIONPROCURADOR, 5) AS PERIODO_TRIMESTRE
       , TO_DATE('01/'|| LPAD(((SUBSTR(ADP.IDFACTURACIONPROCURADOR, 5)-1)*3)+1, 2, '0') ||'/' || SUBSTR(ADP.IDFACTURACIONPROCURADOR, 1, 4), 'DD/MM/YYYY') AS PERIODO_DENDE
       , add_months(TO_DATE('01/'|| LPAD(((SUBSTR(ADP.IDFACTURACIONPROCURADOR, 5)-1)*3)+1, 2, '0') ||'/' || SUBSTR(ADP.IDFACTURACIONPROCURADOR, 1, 4), 'DD/MM/YYYY')-1, 3) AS PERIODO_ATA
       , 'P27028' AS COL_IDCOLEGIO --TODO CARGAR DE TABLA DE BDD CEN_COLEGIOPROCURADOR
       --
        , ADP.NUMEROASUNTO
        , D.ANIO ANIO_DESIGNA
        --, D.CODIGO || DECODE(D.SUFIJO, NULL, '', '-' || D.SUFIJO) AS NUMERO_DESIGNA
        , D.CODIGO AS NUMERO_DESIGNA
        , D.SUFIJO AS SUFIJO_DESIGNA
        , PROC.IDPROCURADOR AS IDCOLEGIADO
        , PROC.NCOLEGIADO AS TO_CODCOLEGIADO
        , ADP.FECHAACTUACION AS TO_FECHAACTUACION
        , EJG.ANIO AS TO_SOX_ANO
        , EJG.NUMEJG AS TO_SOX_NUMERO
        , (SELECT SUBSTR(P.CODIGO, INSTR(P.CODIGO, '-')+1) FROM PCAJG_ICAS P, PCAJG_ICAS_CENINSTITUCION PS
                       WHERE P.IDENTIFICADOR = PS.IDENTIFICADOR
                       AND P.IDINSTITUCION = PS.IDINSTITUCION_PCAJG
                       AND P.IDINSTITUCION = ADP.IDINSTITUCION
                       AND PS.IDINSTITUCION_SIGA = ADP.IDINSTITUCION) AS TO_SOX_COL
        , (CASE
                WHEN EJG.REFAUTO IS NULL OR INSTR(EJG.REFAUTO, '/') = 0
                THEN 'PR'
                ELSE SUBSTR(EJG.REFAUTO, 1, INSTR(EJG.REFAUTO, '/')-1)
                END) AS TO_EXP_CONS--TODO
        , (CASE
               WHEN EJG.REFAUTO IS NULL OR INSTR(EJG.REFAUTO, '/') = 0
               THEN '204A'
               ELSE SUBSTR(EJG.REFAUTO, INSTR(EJG.REFAUTO, '/')+1)
               END) AS TO_EXP_PROC--TODO
        , NVL(EJG.ANIOCAJG, '1900') AS TO_EXP_ANO
        , NVL(EJG.NUMERO_CAJG, '99') AS TO_EXP_NUM
        , (SELECT SUBSTR(P.CODIGO, INSTR(P.CODIGO, '-')+1) FROM PCAJG_ICAS P, PCAJG_ICAS_CENINSTITUCION PS
                       WHERE P.IDENTIFICADOR = PS.IDENTIFICADOR
                       AND P.IDINSTITUCION = PS.IDINSTITUCION_PCAJG
                       AND P.IDINSTITUCION = ADP.IDINSTITUCION
                       AND PS.IDINSTITUCION_SIGA = ADP.IDINSTITUCION) AS TO_EXP_PROV
        , EJG.FECHARESOLUCIONCAJG AS TO_FECHARESOLAXG
        , (CASE
                WHEN INSTR(J.CODIGOEXT, '-') > 0 AND INSTR(J.CODIGOEXT, '/') > 0--FORMATO N-N/N
                THEN SUBSTR(J.CODIGOEXT, INSTR(J.CODIGOEXT, '/')+1)
                ELSE NULL END) AS TO_J_NUMEROSALASECCION
        , SUBSTR(PJ.CODIGOEXT, INSTR(PJ.CODIGOEXT, '-')+1) AS TO_J_PARTIDOXUDICIAL
        , (CASE
               WHEN INSTR(J.CODIGOEXT, '-') > 0 AND INSTR(J.CODIGOEXT, '/') > 0--FORMATO N-N/N
               THEN SUBSTR(J.CODIGOEXT, INSTR(J.CODIGOEXT, '-')+1, INSTR(J.CODIGOEXT, '/')-INSTR(J.CODIGOEXT, '-')-1)
               ELSE NULL END) AS TO_J_COD_ORGANO
        , PP.CODIGOEXT AS TO_J_TIPO_BAREMO --ok CODEXTERNO DE SCS_PROCEDIMIENTOS
        , PP.CODIGO AS TO_J_COD_BAREMO--ok codigo de scs_procedimientos
        , F_SIGA_GETNUMANIOPROC(D.NUMPROCEDIMIENTO, NULL, 'A') AS TO_J_ANO_PROC--ok numero procedimiento
        /*, (CASE INSTR(D.NUMPROCEDIMIENTO, '/')
                   WHEN 0 THEN NULL
                   ELSE SUBSTR(D.NUMPROCEDIMIENTO, INSTR(D.NUMPROCEDIMIENTO, '/')+1, 4)
                   END) AS TO_J_ANO_PROC--ok numero procedimiento*/
        , F_SIGA_GETNUMANIOPROC(D.NUMPROCEDIMIENTO, NULL, 'N') AS TO_J_NUM_PROC--ok numero procedimiento
        /*, (CASE INSTR(D.NUMPROCEDIMIENTO, '/')
                   WHEN 0 THEN NULL
                   ELSE SUBSTR(D.NUMPROCEDIMIENTO, 0, INSTR(D.NUMPROCEDIMIENTO, '/')-1)
                   END) AS TO_J_NUM_PROC--ok numero procedimiento*/
        , DECODE(APP.PORCENTAJE, 100, NULL, round(APP.PORCENTAJE)) AS TO_J_PORCENTAJE
        , DECODE(APP.PORCENTAJE, 100, NULL,
                           (CASE ADP.IDACREDITACION
                                  WHEN 5  --'Extrajudic.'
                                  THEN '801'
                                  WHEN 12 --'Sobreseimiento/Archivo'
                                  THEN '901'
                                  WHEN 13
                                  THEN '803'
                                  WHEN 14
                                  THEN '902'
                                  ELSE NULL END)) AS TO_J_COD_BAREM_POR
        , '     ' AS TO_J_DESC_PROC--ok nulo
        , P.NOMBRE AS TO_S_NOME -- OK EL PRIMERO
        , P.APELLIDO1 AS TO_S_PRIMER_APELLIDO
        , P.APELLIDO2 AS TO_S_SEGUNDO_APELLIDO
        , (SELECT PTI.CODIGO
               FROM PCAJG_TIPO_IDENTIFICACION PTI, PCAJG_TIPO_IDENTIFICACION_CENT PS
               WHERE PTI.IDENTIFICADOR = PS.IDENTIFICADOR
                AND PTI.IDINSTITUCION = PS.IDINSTITUCION
                AND PS.IDTIPOIDENTIFICACION = P.IDTIPOIDENTIFICACION
                AND PS.IDINSTITUCION = P.IDINSTITUCION) AS TO_S_TIPOIDENTIFICADOR
        , P.NIF AS TO_S_NIF
        , PP.PRECIO*APP.PORCENTAJE/100 AS TO_I_IMPORTE --OK IMPORTE FACTURADO PREGUNTAR A ADRIAN
        , 99999.99 AS TO_I_IRPF
        , 1 AS COD_MOTIVO_DEVOLUCION
        , NULL AS DESC_MOTIVO_DEVOLUCION
FROM SCS_ACTUACIONDESIGNAPROCURADOR ADP
     , SCS_PROCURADOR PROC
     , SCS_JUZGADO J
     , CEN_POBLACIONES POB
     , CEN_PARTIDOJUDICIAL PJ
     , SCS_DEFENDIDOSDESIGNA DD--TODO PUEDE TENER MAS DE UN SOLICITANTE
     , SCS_PERSONAJG P
     , SCS_DESIGNA D
     , SCS_EJGDESIGNA ED
     , SCS_EJG EJG
     , SCS_ACREDIT_PROCPROCURADOR APP
     , SCS_PROCEDIMIENTOSPROCURADORES PP
WHERE ADP.IDINSTITUCION_PROC = PROC.IDINSTITUCION
AND ADP.IDPROCURADOR = PROC.IDPROCURADOR
AND ADP.IDINSTITUCION = J.IDINSTITUCION
AND ADP.IDJUZGADO = J.IDJUZGADO
AND J.IDPOBLACION = POB.IDPOBLACION(+)
AND POB.IDPARTIDO = PJ.IDPARTIDO(+)
AND ADP.IDINSTITUCION = DD.IDINSTITUCION(+)
AND ADP.IDTURNO = DD.IDTURNO(+)
AND ADP.ANIO = DD.ANIO(+)
AND ADP.NUMERO = DD.NUMERO(+)
AND (DD.IDPERSONA IS NULL OR DD.IDPERSONA = (SELECT MAX(DD2.IDPERSONA) FROM SCS_DEFENDIDOSDESIGNA DD2 WHERE DD2.IDINSTITUCION = DD.IDINSTITUCION
    AND DD2.IDTURNO = DD.IDTURNO AND DD2.ANIO = DD.ANIO AND DD2.NUMERO = DD.NUMERO))--SI HAY MAS DE UNA PERSONA COGEMOS UNA AL AZAR
AND DD.IDINSTITUCION = P.IDINSTITUCION(+)
AND DD.IDPERSONA = P.IDPERSONA(+)
AND ADP.IDINSTITUCION = D.IDINSTITUCION
AND ADP.IDTURNO = D.IDTURNO
AND ADP.ANIO = D.ANIO
AND ADP.NUMERO = D.NUMERO
AND D.IDINSTITUCION = ED.IDINSTITUCION(+)
AND D.IDTURNO = ED.IDTURNO(+)
AND D.ANIO = ED.ANIODESIGNA(+)
AND D.NUMERO = ED.NUMERODESIGNA(+)
AND (ED.NUMEROEJG IS NULL OR ((ED.ANIOEJG || LPAD(ED.NUMEROEJG, 10, '0')) =
    (SELECT MIN(ED2.ANIOEJG || LPAD(ED2.NUMEROEJG, 10, '0'))
            FROM SCS_EJGDESIGNA ED2
            WHERE ED2.IDINSTITUCION = ED.IDINSTITUCION
            AND ED2.IDTURNO = ED.IDTURNO
            AND ED2.ANIODESIGNA = ED.ANIODESIGNA
            AND ED2.NUMERODESIGNA = ED.NUMERODESIGNA)))--SI HAY MAS DE UN EJG COGEMOS EL PRIMERO
AND ED.IDINSTITUCION = EJG.IDINSTITUCION(+)
AND ED.IDTIPOEJG = EJG.IDTIPOEJG(+)
AND ED.ANIOEJG = EJG.ANIO(+)
AND ED.NUMEROEJG = EJG.NUMERO(+)
AND ADP.IDINSTITUCION = APP.IDINSTITUCION
AND ADP.IDPROCEDIMIENTOPROCURADOR = APP.IDPROCEDIMIENTOPROCURADOR
AND ADP.IDACREDITACION = APP.IDACREDITACION
AND APP.IDINSTITUCION = PP.IDINSTITUCION
AND APP.IDPROCEDIMIENTOPROCURADOR = PP.IDPROCEDIMIENTOPROCURADOR
AND ADP.IDFACTURACIONPROCURADOR = 20124
ORDER BY PROC.IDPROCURADOR

